import { TechnicalQuestion } from '../../src/types';

export const CLOUD_QUESTIONS: TechnicalQuestion[] = [
  // Level 1 — Basic (10 Questions)
  {
    question_id: 'cloud_l1_q1',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Docker Basics',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Docker and why do software teams use containers?',
    expected_key_points: ['Packages application with all its dependencies and runtime', 'Ensures code runs identically across dev, test, and production', 'Lightweight and fast startup compared to virtual machines'],
    improved_answer: 'Docker is a containerization platform that packages an application along with its dependencies, libraries, and configurations into a container image, eliminating the "works on my machine" problem across different environments.',
  },
  {
    question_id: 'cloud_l1_q2',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Containers vs VMs',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the key difference between a Docker container and a Virtual Machine?',
    expected_key_points: ['Containers share the host OS kernel', 'VMs run a full guest operating system on top of a hypervisor', 'Containers are lighter, smaller, and boot in seconds'],
    improved_answer: 'Containers share the host operating system kernel and isolate processes, making them lightweight and fast to boot. Virtual Machines include a full guest OS on a hypervisor, consuming significantly more CPU, memory, and disk space.',
  },
  {
    question_id: 'cloud_l1_q3',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Dockerfile Instructions',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'In a Dockerfile, what is the difference between RUN and CMD?',
    expected_key_points: ['RUN executes during image build time (e.g. npm install)', 'CMD specifies the default command executed when the container starts', 'RUN creates a new image layer; CMD provides default runtime parameters'],
    improved_answer: 'RUN executes commands during the image build process to install dependencies and configure the filesystem. CMD defines the default command and arguments that run when the container is launched.',
  },
  {
    question_id: 'cloud_l1_q4',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'CI/CD Pipeline',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is CI/CD and what are the benefits of automating it?',
    expected_key_points: ['CI (Continuous Integration): automatically build and test code on every commit', 'CD (Continuous Delivery/Deployment): automatically deploy verified code to servers', 'Catches bugs early and speeds up release cycles'],
    improved_answer: 'CI/CD automates the software delivery lifecycle. Continuous Integration tests and builds code automatically upon every git push, while Continuous Deployment releases approved builds to production without manual intervention.',
  },
  {
    question_id: 'cloud_l1_q5',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Kubernetes Pod',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a Pod in Kubernetes?',
    expected_key_points: ['Smallest deployable execution unit in Kubernetes', 'Encapsulates one or more containers sharing network IP and storage volumes', 'Treated as ephemeral'],
    improved_answer: 'A Pod is the smallest deployable unit in Kubernetes. It encapsulates one or more containers that share the same network namespace (IP address), storage volumes, and runtime specification.',
  },
  {
    question_id: 'cloud_l1_q6',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Cloud Deployment Models',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between Public Cloud, Private Cloud, and Hybrid Cloud?',
    expected_key_points: ['Public: infrastructure owned and shared by third-party provider (AWS/GCP)', 'Private: infrastructure exclusively used by a single organization', 'Hybrid: combination of on-premise private infrastructure and public cloud'],
    improved_answer: 'Public cloud services (AWS, Google Cloud) are multi-tenant and managed by third parties. Private cloud is dedicated entirely to one organization on private hardware. Hybrid cloud connects both environments securely.',
  },
  {
    question_id: 'cloud_l1_q7',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Infrastructure as Code',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Infrastructure as Code (IaC) and what are its benefits?',
    expected_key_points: ['Managing servers, networks, and databases using declarative code files (e.g. Terraform)', 'Version controlled, reproducible, and eliminates human manual configuration errors', 'Fast automated provisioning and teardown'],
    improved_answer: 'Infrastructure as Code (IaC) is the practice of provisioning and managing cloud infrastructure using declarative code files (like Terraform). It allows teams to version control, automate, and reproduce environments reliably.',
  },
  {
    question_id: 'cloud_l1_q8',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Reverse Proxy & NGINX',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a reverse proxy (like NGINX) and why is it placed in front of web servers?',
    expected_key_points: ['Sits between client and backend servers', 'Handles SSL termination, load balancing, caching, and security filtering', 'Hides backend server IPs and internal topology'],
    improved_answer: 'A reverse proxy intercepts client requests and forwards them to backend servers. It handles SSL/TLS termination, balances incoming traffic across multiple instances, serves static assets, and shields internal server IPs.',
  },
  {
    question_id: 'cloud_l1_q9',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Horizontal vs Vertical Scaling',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between horizontal scaling and vertical scaling?',
    expected_key_points: ['Vertical (scaling up): adding more CPU and RAM to an existing single machine', 'Horizontal (scaling out): adding more machines or container instances to distribute load', 'Horizontal scaling is resilient with no single point of failure'],
    improved_answer: 'Vertical scaling upgrades an existing server with more CPU and RAM, but has hardware ceilings and a single point of failure. Horizontal scaling adds more server instances behind a load balancer, providing infinite scaling and high availability.',
  },
  {
    question_id: 'cloud_l1_q10',
    domain: 'cloud',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Environment Variables',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'Why should sensitive credentials and API keys be passed as environment variables rather than hardcoded in source code?',
    expected_key_points: ['Prevents accidental leakage in git repositories', 'Allows different configs per environment (dev, staging, prod)', 'Complies with 12-factor app security principles'],
    improved_answer: 'Hardcoding secrets in source code risks exposing them publicly via version control. Environment variables keep secrets separate from code and enable different configurations for development, staging, and production.',
  },

  // Level 2 — Intermediate (10 Questions)
  {
    question_id: 'cloud_l2_q1',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Kubernetes Deployments',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a Kubernetes Deployment and how does it ensure high availability?',
    expected_key_points: ['Declares desired state (e.g. 3 replica Pods)', 'ReplicaSet controller automatically replaces failed or crashed Pods', 'Manages zero-downtime rolling updates and rollbacks'],
    improved_answer: 'A Kubernetes Deployment declares the desired state for a set of Pod replicas. If a Pod crashes, the Deployment controller automatically provisions a new one. It also coordinates rolling updates with zero downtime.',
  },
  {
    question_id: 'cloud_l2_q2',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Kubernetes Service Types',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between ClusterIP, NodePort, and LoadBalancer Kubernetes services?',
    expected_key_points: ['ClusterIP: internal cluster-only IP (default)', 'NodePort: exposes service on a static port on each node IP', 'LoadBalancer: provisions an external cloud load balancer (AWS ELB, GCP LB)'],
    improved_answer: 'ClusterIP exposes the service on an internal IP reachable only inside the cluster. NodePort opens a dedicated port on each worker node IP. LoadBalancer provisions an external cloud provider load balancer with a public IP.',
  },
  {
    question_id: 'cloud_l2_q3',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Terraform State',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the terraform.tfstate file and why is it stored remotely (e.g. S3 with DynamoDB lock)?',
    expected_key_points: ['Maps declared configuration to real-world cloud resources', 'Tracks metadata and resource IDs', 'Remote backend prevents race conditions and team conflicts via state locking'],
    improved_answer: 'The Terraform state file tracks the current status and IDs of all provisioned cloud resources. Storing it in a remote backend (like AWS S3) with locking (DynamoDB) prevents concurrent team updates from corrupting infrastructure.',
  },
  {
    question_id: 'cloud_l2_q4',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Blue-Green vs Canary Deployments',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between a Blue-Green deployment and a Canary deployment?',
    expected_key_points: ['Blue-Green: runs two identical environments; switches all router traffic from Blue to Green at once', 'Canary: routes a small percentage of traffic (e.g. 5%) to new version to test in production', 'Both minimize downtime and risk'],
    improved_answer: 'Blue-Green maintains two identical environments and cuts 100% of traffic over instantly when Green is ready. Canary gradually routes a small slice of live traffic (e.g. 5%) to the new build to monitor error rates before full rollout.',
  },
  {
    question_id: 'cloud_l2_q5',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'VPC and Subnets',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a Virtual Private Cloud (VPC) and what is the difference between public and private subnets?',
    expected_key_points: ['VPC is an isolated virtual network in the cloud', 'Public subnet has route to an Internet Gateway and public IPs', 'Private subnet has no direct internet route and communicates via NAT Gateway'],
    improved_answer: 'A VPC is an isolated network within a cloud provider. Public subnets have direct routes to an Internet Gateway for web-facing load balancers, while private subnets host databases and backend services isolated from direct internet access.',
  },
  {
    question_id: 'cloud_l2_q6',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Docker COPY vs ADD',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'In a Dockerfile, when should you use COPY instead of ADD?',
    expected_key_points: ['COPY simply copies files from host to image filesystem', 'ADD can extract tar archives and download from remote URLs', 'Best practice is to use COPY for transparency and predictability'],
    improved_answer: 'COPY is the preferred instruction for copying local files into the container. ADD has extra behavior—automatically unpacking tar archives and fetching remote URLs—which can lead to unintended side effects.',
  },
  {
    question_id: 'cloud_l2_q7',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Prometheus & Grafana',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What are Prometheus and Grafana, and how do they work together?',
    expected_key_points: ['Prometheus scrapes and stores time-series numerical metrics via pull model', 'Grafana connects to Prometheus to render interactive visualization dashboards and alerts'],
    improved_answer: 'Prometheus is a time-series monitoring system that scrapes metrics (CPU, RAM, HTTP request counts) from application endpoints. Grafana is a visualization tool that queries Prometheus to display live dashboards and trigger alerts.',
  },
  {
    question_id: 'cloud_l2_q8',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Load Balancing Algorithms',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'Name two common load balancing algorithms and explain how they distribute traffic.',
    expected_key_points: ['Round Robin: cycles through servers sequentially', 'Least Connections: sends traffic to server with fewest active connections', 'IP Hash: maps client IP to a specific server for session affinity'],
    improved_answer: 'Round Robin routes incoming requests sequentially across the list of healthy servers. Least Connections directs new traffic to whichever server currently has the lowest number of active client sessions.',
  },
  {
    question_id: 'cloud_l2_q9',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'API Gateway',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the role of an API Gateway in a microservices architecture?',
    expected_key_points: ['Single entry point for all client requests', 'Handles cross-cutting concerns: routing, authentication, rate limiting, and SSL', 'Prevents exposing internal microservices directly to the web'],
    improved_answer: 'An API Gateway serves as the single public entry point for client requests in a microservices architecture, managing routing, user authentication, rate limiting, and request transformation in one central layer.',
  },
  {
    question_id: 'cloud_l2_q10',
    domain: 'cloud',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'SSL/TLS Termination',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is SSL/TLS termination at the load balancer level and why is it done?',
    expected_key_points: ['Load balancer decrypts incoming HTTPS traffic using SSL certificates', 'Passes unencrypted HTTP traffic to backend servers in private network', 'Offloads CPU-heavy encryption from application servers'],
    improved_answer: 'SSL/TLS termination decrypts HTTPS requests at the load balancer or reverse proxy before forwarding clean HTTP traffic to backend servers over the private network, freeing backend servers from cryptographic overhead.',
  },

  // Level 3 — Practical & Coding (10 Questions)
  {
    question_id: 'cloud_l3_q1',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Multi-stage Dockerfile',
    difficulty: 'Hard',
    type: 'coding',
    language: 'dockerfile',
    question: 'Write a simple multi-stage Dockerfile for a Node.js app that keeps the final production image small.',
    code_template: `# Stage 1: Build
FROM node:20-alpine AS builder
# ... write build steps

# Stage 2: Production Runner
FROM node:20-alpine AS runner
# ... write runner steps`,
    expected_key_points: ['Build stage compiles code and installs devDependencies', 'Production stage copies only dist and production node_modules', 'Uses alpine base image to minimize footprint'],
    improved_answer: `# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS runner
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
CMD ["node", "dist/index.js"]`,
  },
  {
    question_id: 'cloud_l3_q2',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'GitHub Actions Workflow',
    difficulty: 'Hard',
    type: 'coding',
    language: 'yaml',
    question: 'Write a basic GitHub Actions workflow YAML file that runs automated tests whenever code is pushed to the main branch.',
    code_template: `name: CI Test
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # add steps`,
    expected_key_points: ['actions/checkout@v4 to check out repository', 'actions/setup-node to configure Node.js runtime', 'npm ci and npm test commands'],
    improved_answer: `name: CI Test
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test`,
  },
  {
    question_id: 'cloud_l3_q3',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'CrashLoopBackOff Troubleshooting',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'A Kubernetes Pod status is CrashLoopBackOff. What exact kubectl commands do you run to diagnose and fix it?',
    expected_key_points: ['kubectl logs <pod-name> to inspect application crash logs', 'kubectl describe pod <pod-name> to check OOMKilled or failed probes', 'Check environment variables, secrets, and database connectivity'],
    improved_answer: '1) Run kubectl logs <pod-name> (or --previous) to view unhandled app exceptions. 2) Run kubectl describe pod <pod-name> to see if it was terminated with OOMKilled (out of memory) or failing readiness/liveness probes.',
  },
  {
    question_id: 'cloud_l3_q4',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'High Availability Architecture',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do you design a high-availability cloud architecture that survives the failure of an entire data center region or Availability Zone?',
    expected_key_points: ['Deploy instances across multiple Availability Zones (Multi-AZ)', 'Use an Application Load Balancer spanning AZs', 'Use multi-AZ managed databases with automatic failover (e.g. AWS RDS Multi-AZ)'],
    improved_answer: 'Distribute app instances across at least three Availability Zones behind a regional load balancer. Use a managed database with automated Multi-AZ standby replication and auto-failover, ensuring continuous uptime if an AZ goes dark.',
  },
  {
    question_id: 'cloud_l3_q5',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Linux High CPU Troubleshooting',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'A production Linux server reports 100% CPU usage. What commands do you run to identify the offending process and diagnose it?',
    expected_key_points: ['top or htop to find highest CPU consuming PID', 'ps aux --sort=-%cpu | head -10', 'Check logs using journalctl or application logs'],
    improved_answer: '1) Run "top" or "htop" to instantly view the process ID (PID) consuming CPU. 2) Run "ps aux --sort=-%cpu | head -10" for process details. 3) Inspect application logs or generate thread dumps to pinpoint the runaway loop.',
  },
  {
    question_id: 'cloud_l3_q6',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Managing Cloud Secrets',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How should you securely pass database passwords to Kubernetes Pods without committing them to git?',
    expected_key_points: ['Use Kubernetes Secrets or cloud secret managers (AWS Secrets Manager, HashiCorp Vault)', 'Inject secrets as environment variables or mounted volume files', 'Use External Secrets Operator to sync securely'],
    improved_answer: 'Store database credentials in a cloud secret manager (like AWS Secrets Manager or HashiCorp Vault). Use the Kubernetes External Secrets Operator or Sealed Secrets to inject values into Pods at runtime without checking secrets into git.',
  },
  {
    question_id: 'cloud_l3_q7',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Database Disaster Recovery',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What is RPO and RTO in disaster recovery, and how do automated backups help achieve them?',
    expected_key_points: ['RPO (Recovery Point Objective): maximum acceptable data loss measured in time', 'RTO (Recovery Time Objective): maximum acceptable downtime to restore service', 'Automated point-in-time recovery and snapshot replication achieve low RPO and RTO'],
    improved_answer: 'RPO (Recovery Point Objective) is the maximum acceptable data loss timeframe (e.g. 5 minutes of data). RTO (Recovery Time Objective) is the target time to restore service (e.g. 30 minutes). Point-in-time database snapshots help satisfy both.',
  },
  {
    question_id: 'cloud_l3_q8',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Zero-Downtime Rolling Update',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do readiness probes and liveness probes in Kubernetes prevent downtime during rolling updates?',
    expected_key_points: ['Readiness probe checks if container is ready to accept user traffic', 'Traffic is routed to new Pod only after readiness check passes', 'Liveness probe restarts container if it freezes or deadlocks'],
    improved_answer: 'During a rolling update, Kubernetes starts the new Pod but will not route network traffic to it until its readiness probe returns HTTP 200. This ensures old Pods continue handling requests until new Pods are fully booted.',
  },
  {
    question_id: 'cloud_l3_q9',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Securing Kubernetes Clusters',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What are two essential security practices to harden a Kubernetes cluster?',
    expected_key_points: ['Role-Based Access Control (RBAC) with principle of least privilege', 'Run containers as non-root users with read-only root filesystems', 'Network policies to restrict inter-pod communications'],
    improved_answer: '1) Enforce RBAC with least privilege so service accounts cannot perform admin actions. 2) Set securityContext in Pod specs to run containers as non-root users (runAsNonRoot: true) and restrict inter-pod traffic with NetworkPolicies.',
  },
  {
    question_id: 'cloud_l3_q10',
    domain: 'cloud',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Alerting on API Spikes',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How would you set up Prometheus Alertmanager to alert on-call engineers when HTTP 500 error rates exceed 5% over 5 minutes?',
    expected_key_points: ['Write PromQL query calculating ratio of 5xx errors to total requests', 'Define alert rule with "for: 5m" condition', 'Route alert to PagerDuty or Slack via Alertmanager'],
    improved_answer: 'Define a Prometheus alert rule comparing rate(http_requests_total{status=~"5.."}[5m]) divided by total requests rate. If the ratio > 0.05 for 5 minutes, Alertmanager automatically fires a high-severity notification to PagerDuty.',
  },
];
