import { TechnicalQuestion } from '../../src/types';

export const CYBERSECURITY_QUESTIONS: TechnicalQuestion[] = [
  // Level 1 — Basic (10 Questions)
  {
    question_id: 'sec_l1_q1',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'CIA Triad',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the CIA Triad in information security, and what does each pillar stand for?',
    expected_key_points: ['Confidentiality (prevent unauthorized disclosure)', 'Integrity (prevent unauthorized modification)', 'Availability (ensure authorized access when needed)'],
    improved_answer: 'The CIA Triad consists of Confidentiality (protecting data from unauthorized disclosure), Integrity (ensuring data is accurate and untampered), and Availability (guaranteeing authorized users have reliable access when needed).',
  },
  {
    question_id: 'sec_l1_q2',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Authentication vs Authorization',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between Authentication and Authorization?',
    expected_key_points: ['Authentication: verifying who the user is (e.g. login credentials, biometric)', 'Authorization: determining what permissions or resources the authenticated user can access'],
    improved_answer: 'Authentication verifies identity ("Who are you?"), such as verifying a password or fingerprint. Authorization determines permissions ("What are you allowed to do?"), such as checking if a user has admin privileges.',
  },
  {
    question_id: 'sec_l1_q3',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Phishing Attacks',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Phishing and how do attackers trick unsuspecting users?',
    expected_key_points: ['Social engineering attack using deceptive emails or websites', 'Impersonates trustworthy entities (banks, employers, IT support)', 'Tricks users into revealing passwords, credentials, or installing malware'],
    improved_answer: 'Phishing is a social engineering attack where an attacker impersonates a trusted entity (such as a bank or colleague) in emails or fake websites to trick victims into revealing sensitive credentials or downloading malicious attachments.',
  },
  {
    question_id: 'sec_l1_q4',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Malware Types',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between a Computer Virus and Ransomware?',
    expected_key_points: ['Virus: malicious code that attaches to files and replicates across systems', 'Ransomware: encrypts victim files and demands payment/ransom for decryption key'],
    improved_answer: 'A computer virus infects files and replicates by attaching itself to legitimate programs. Ransomware encrypts the victim files or system storage and demands a cryptocurrency payment in exchange for the decryption key.',
  },
  {
    question_id: 'sec_l1_q5',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Firewalls',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a Firewall and how does it protect a network?',
    expected_key_points: ['Network security device monitoring incoming and outgoing traffic', 'Blocks or allows packets based on predefined security rules', 'Acts as a barrier between secure internal network and untrusted public internet'],
    improved_answer: 'A firewall is a security barrier that monitors and filters incoming and outgoing network traffic based on established security rules, blocking unauthorized access attempts from the public internet.',
  },
  {
    question_id: 'sec_l1_q6',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'HTTP vs HTTPS',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between HTTP and HTTPS, and why does HTTPS matter?',
    expected_key_points: ['HTTP sends plain text data vulnerable to eavesdropping and interception', 'HTTPS uses TLS/SSL encryption to encrypt traffic in transit', 'Ensures privacy, integrity, and server authentication'],
    improved_answer: 'HTTP transmits all data as plaintext, allowing eavesdroppers to intercept passwords. HTTPS encrypts traffic using TLS/SSL, guaranteeing data confidentiality and verifying the legitimate identity of the web server.',
  },
  {
    question_id: 'sec_l1_q7',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'MFA / 2FA',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Multi-Factor Authentication (MFA) and what are the three classic authentication factors?',
    expected_key_points: ['Something you know (password, PIN)', 'Something you have (phone, security key, authenticator app)', 'Something you are (biometrics: fingerprint, face recognition)'],
    improved_answer: 'MFA requires two or more independent factors to verify identity: Something you know (password), Something you have (authenticator app or hardware token), and Something you are (biometric fingerprint or facial scan).',
  },
  {
    question_id: 'sec_l1_q8',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Brute Force Attacks',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a Brute Force attack, and how do applications prevent it?',
    expected_key_points: ['Attacker tries every possible combination of passwords or keys until finding the match', 'Prevent using account lockouts after N failed attempts', 'Use rate limiting, CAPTCHAs, and strong password complexity policies'],
    improved_answer: 'A brute-force attack systematically guesses every possible character combination to crack passwords. Applications defend against it using account lockouts after 5 failed tries, IP rate limiting, and CAPTCHAs.',
  },
  {
    question_id: 'sec_l1_q9',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Vulnerability vs Threat vs Risk',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between a Vulnerability, a Threat, and a Risk in cybersecurity?',
    expected_key_points: ['Vulnerability: a flaw or weakness in software or configuration', 'Threat: an external actor or event that could exploit a vulnerability', 'Risk: probability and impact of a threat exploiting a vulnerability'],
    improved_answer: 'A vulnerability is an internal weakness or bug in a system. A threat is an attacker or event with the capability to exploit that weakness. Risk is the product of likelihood and impact if the threat exploits the vulnerability.',
  },
  {
    question_id: 'sec_l1_q10',
    domain: 'cybersecurity',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Hashing vs Encryption',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the fundamental difference between Hashing and Encryption?',
    expected_key_points: ['Hashing is one-way: plaintext cannot be reversed from the hash', 'Encryption is two-way: ciphertext can be decrypted back to plaintext with a key', 'Hashing is used for password storage and data integrity; encryption is for data confidentiality'],
    improved_answer: 'Hashing is a one-way mathematical function (e.g. SHA-256, bcrypt) that cannot be reversed. Encryption is a reversible two-way process that transforms data into ciphertext, which can be decrypted back to plaintext using a secret key.',
  },

  // Level 2 — Intermediate (10 Questions)
  {
    question_id: 'sec_l2_q1',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'SQL Injection Prevention',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is SQL Injection (SQLi) and what is the definitive way to prevent it?',
    expected_key_points: ['Attacker injects malicious SQL fragments into input fields to manipulate database queries', 'Definitive defense: parameterized queries / prepared statements', 'Use Object-Relational Mappers (ORMs) and input validation'],
    improved_answer: 'SQL Injection occurs when untrusted user input is concatenated directly into SQL queries. The primary defense is parameterized queries (prepared statements), which treat input strictly as literal values rather than executable code.',
  },
  {
    question_id: 'sec_l2_q2',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Cross-Site Scripting (XSS)',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Cross-Site Scripting (XSS) and what are its three main types?',
    expected_key_points: ['Stored XSS (malicious script saved in database)', 'Reflected XSS (malicious script reflected in URL or error response)', 'DOM-based XSS (client-side script executes unsafe inputs in the browser DOM)'],
    improved_answer: 'XSS injects malicious client-side JavaScript into web pages viewed by other users. The three types are Stored XSS (persisted in DB), Reflected XSS (executed via URL queries), and DOM-based XSS (executed directly via browser DOM manipulation).',
  },
  {
    question_id: 'sec_l2_q3',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Symmetric vs Asymmetric Encryption',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between Symmetric and Asymmetric encryption?',
    expected_key_points: ['Symmetric uses one single secret key for both encryption and decryption (AES)', 'Asymmetric uses a key pair: public key to encrypt, private key to decrypt (RSA, ECC)', 'Symmetric is fast for bulk data; asymmetric is used for key exchange and digital signatures'],
    improved_answer: 'Symmetric encryption (like AES-256) uses the same secret key to encrypt and decrypt data, making it fast for large payloads. Asymmetric encryption (like RSA) uses a public key to encrypt and a separate private key to decrypt.',
  },
  {
    question_id: 'sec_l2_q4',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'DDoS Mitigation',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a Distributed Denial of Service (DDoS) attack and how can it be mitigated?',
    expected_key_points: ['Overwhelms target servers with massive traffic from thousands of infected botnet machines', 'Mitigate using Cloudflare/AWS Shield edge scrubbing networks, rate limiting, and Anycast routing'],
    improved_answer: 'A DDoS attack floods a service with malicious traffic from distributed botnets to exhaust server bandwidth and memory. Mitigation involves Anycast routing, CDN edge caching, web application firewalls (WAF), and scrubbing providers like Cloudflare.',
  },
  {
    question_id: 'sec_l2_q5',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'CSRF Attacks',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Cross-Site Request Forgery (CSRF) and how do Anti-CSRF tokens work?',
    expected_key_points: ['Tricks authenticated user browser into executing unwanted actions on another site', 'Anti-CSRF token: unpredictable, secret token generated by server per session', 'Server rejects any state-changing request missing the valid token'],
    improved_answer: 'CSRF tricks an authenticated user into submitting an unauthorized request to a trusted site. Anti-CSRF tokens generate a secret, unpredictable token tied to the user session; POST requests must include this token or the server rejects them.',
  },
  {
    question_id: 'sec_l2_q6',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Zero Trust Architecture',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Zero Trust Architecture and what does the motto "Never Trust, Always Verify" mean?',
    expected_key_points: ['Eliminates concept of trusted internal corporate network', 'Every user, device, and connection must be authenticated and authorized continually', 'Micro-segmentation and least privilege access'],
    improved_answer: 'Zero Trust assumes threats exist both outside and inside the network. Instead of trusting internal corporate IP ranges, it requires continuous verification of user identity, device health, and least privilege access for every single request.',
  },
  {
    question_id: 'sec_l2_q7',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Man-in-the-Middle (MITM)',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'How does an attacker perform a Man-in-the-Middle (MITM) attack, and how does TLS certificate validation stop it?',
    expected_key_points: ['Attacker intercepts communication between client and server (e.g. rogue Wi-Fi hotspot)', 'TLS certificates signed by trusted Certificate Authorities (CAs) prove server authenticity', 'Client rejects connections with untrusted or mismatched certificates'],
    improved_answer: 'In a MITM attack, an attacker sits between client and server to read or tamper with traffic. TLS prevents this because the server must present a digital certificate signed by a trusted Certificate Authority that matches the requested domain.',
  },
  {
    question_id: 'sec_l2_q8',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Principle of Least Privilege',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the Principle of Least Privilege in access management (IAM)?',
    expected_key_points: ['Users, services, and applications are granted only the minimum permissions necessary to complete their job', 'Minimizes blast radius in case credentials are compromised'],
    improved_answer: 'The Principle of Least Privilege dictates that users, processes, and service accounts receive only the bare minimum permissions required to perform their duties, strictly limiting damage if an account is compromised.',
  },
  {
    question_id: 'sec_l2_q9',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Public Key Infrastructure (PKI)',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a Certificate Authority (CA) in Public Key Infrastructure?',
    expected_key_points: ['Trusted third-party organization verifying domain ownership', 'Digitally signs TLS/SSL certificates with its private key', 'Operating systems and browsers ship with trusted root CA certificates'],
    improved_answer: 'A Certificate Authority (like Let’s Encrypt or DigiCert) is a trusted entity that verifies domain ownership and issues cryptographically signed digital certificates. Browsers trust these certificates because the CA root certificate is pre-installed in the OS.',
  },
  {
    question_id: 'sec_l2_q10',
    domain: 'cybersecurity',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Penetration Testing vs Vulnerability Scan',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between an automated Vulnerability Scan and an ethical Penetration Test?',
    expected_key_points: ['Vulnerability scan: automated tool finding known CVE vulnerabilities and missing patches', 'Penetration test: human security professional actively attempting to exploit weaknesses to breach systems'],
    improved_answer: 'A vulnerability scan is an automated tool scanning for known unpatched software bugs. A penetration test is an active, manual simulation conducted by human ethical hackers attempting to chain exploits and compromise the target system.',
  },

  // Level 3 — Practical & Coding (10 Questions)
  {
    question_id: 'sec_l3_q1',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Input Sanitization Function',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a JavaScript function to escape HTML special characters to prevent Cross-Site Scripting (XSS).',
    code_template: `function escapeHTML(str) {
  // Replace &, <, >, ", ' with HTML entities
}`,
    expected_key_points: ['Escape & to &amp;', 'Escape < to &lt; and > to &gt;', 'Escape " to &quot; and \' to &#x27;'],
    improved_answer: `function escapeHTML(str) {
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#x27;',
  };
  return str.replace(/[&<>"']/g, (char) => map[char]);
}`,
  },
  {
    question_id: 'sec_l3_q2',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Password Strength Validator',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a function that validates if a password has at least 8 characters, 1 uppercase, 1 lowercase, 1 number, and 1 special symbol.',
    code_template: `function isPasswordStrong(password) {
  // Return boolean
}`,
    expected_key_points: ['Check min length >= 8', 'Test /[A-Z]/, /[a-z]/, /[0-9]/, and /[^A-Za-z0-9]/', 'Return true only if all criteria pass'],
    improved_answer: `function isPasswordStrong(password) {
  if (!password || password.length < 8) return false;
  const hasUpper = /[A-Z]/.test(password);
  const hasLower = /[a-z]/.test(password);
  const hasNum = /[0-9]/.test(password);
  const hasSpecial = /[^A-Za-z0-9]/.test(password);
  return hasUpper && hasLower && hasNum && hasSpecial;
}`,
  },
  {
    question_id: 'sec_l3_q3',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Ransomware Incident Response',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'An employee workstation just displayed a ransomware note. What are your immediate first 3 incident response actions?',
    expected_key_points: ['Immediately isolate infected machine from network (unplug Ethernet, disable Wi-Fi)', 'Do NOT shut down immediately if volatile RAM memory needs preservation', 'Alert security team, assess scope of infection, and verify clean offline backups'],
    improved_answer: '1) Immediately isolate: disconnect the affected device from the local network and Wi-Fi to stop lateral spread. 2) Preserve evidence: capture RAM forensics if possible. 3) Assess scope and restore clean data from isolated, immutable backups.',
  },
  {
    question_id: 'sec_l3_q4',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Password Storage with Bcrypt',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'Why should you never store passwords using plain SHA-256 or MD5, and why is bcrypt or Argon2 preferred?',
    expected_key_points: ['MD5 and SHA-256 are extremely fast, allowing GPU clusters to test billions of hashes per second', 'Vulnerable to precomputed rainbow tables without salts', 'bcrypt and Argon2 are slow, work-factor configurable, and auto-generate unique random salts'],
    improved_answer: 'MD5 and SHA-256 are general-purpose hashes optimized for speed; modern GPUs can test billions of guesses per second with rainbow tables. Key-derivation functions like bcrypt or Argon2 introduce configurable computational work factors and unique salts to make brute forcing infeasible.',
  },
  {
    question_id: 'sec_l3_q5',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Securing Payment APIs',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do you ensure credit card information processed by your API meets PCI-DSS compliance?',
    expected_key_points: ['Never store raw credit card numbers or CVVs on your servers', 'Use third-party tokenization (Stripe Elements / PayPal SDK)', 'Transmit all data over TLS 1.3 encryption and tokenize immediately'],
    improved_answer: 'Never let raw card data touch your backend servers. Use client-side tokenization (like Stripe.js or Apple Pay SDK), where cards are sent directly to the payment processor from the user browser, returning only an opaque token to your backend.',
  },
  {
    question_id: 'sec_l3_q6',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Preventing Session Hijacking',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What cookie flags and architecture practices prevent Session Hijacking?',
    expected_key_points: ['HttpOnly flag prevents access via JavaScript (blocks XSS theft)', 'Secure flag ensures cookie is only sent over HTTPS', 'SameSite=Lax or Strict blocks CSRF cross-origin transmission', 'Regenerate session ID upon login'],
    improved_answer: 'Set session cookies with HttpOnly (blocks JavaScript theft), Secure (transmits only over HTTPS), and SameSite=Strict (blocks CSRF). Also regenerate the session ID upon authentication to prevent session fixation attacks.',
  },
  {
    question_id: 'sec_l3_q7',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Cloud Storage Bucket Data Leaks',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do you guarantee cloud storage buckets (AWS S3, GCP Cloud Storage) never leak private files to the public internet?',
    expected_key_points: ['Enable account-level "Block Public Access" feature', 'Enforce IAM bucket policies and least privilege access', 'Use pre-signed URLs with short expiration for authorized user downloads'],
    improved_answer: 'Enable cloud-wide "Block Public Access" settings, remove all wildcard (*) permissions from bucket policies, and serve private user files using temporary pre-signed URLs that expire in 10 minutes.',
  },
  {
    question_id: 'sec_l3_q8',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Credential Stuffing Defense',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What is Credential Stuffing, and how do you protect your login page from it?',
    expected_key_points: ['Attackers use lists of leaked username/password combos from past breaches to automate logins on other sites', 'Defend using IP rate limiting, CAPTCHA on failed attempts, and enforcing MFA'],
    improved_answer: 'Credential stuffing automates logins using credentials leaked in previous third-party breaches. Defense includes rate limiting login attempts by IP and username, triggering CAPTCHAs, checking passwords against HaveIBeenPwned API, and requiring MFA.',
  },
  {
    question_id: 'sec_l3_q9',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Zero-Day Vulnerability Defense',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What is a Zero-Day vulnerability, and how can an organization defend its infrastructure before a security patch is released?',
    expected_key_points: ['Flaw unknown to software vendor with zero days to patch', 'Deploy Web Application Firewall (WAF) virtual patching rules', 'Disable affected features or isolate affected network segments', 'Monitor abnormal process and egress traffic behavior'],
    improved_answer: 'A Zero-Day is a vulnerability unknown to the software vendor. Before an official patch exists, organizations defend by applying virtual patch rules in their WAF, disabling vulnerable components, restricting egress network access, and actively monitoring SIEM alerts.',
  },
  {
    question_id: 'sec_l3_q10',
    domain: 'cybersecurity',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Security Code Review Best Practices',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'During a pull request code review, what are three critical security red flags you should look for?',
    expected_key_points: ['Hardcoded secrets, API keys, or private tokens in code or config', 'Unsanitized user inputs passed directly into SQL queries or HTML', 'Missing authorization checks on sensitive backend API endpoints'],
    improved_answer: '1) Hardcoded credentials or API keys. 2) Direct concatenation of user input into SQL queries, shells, or HTML (SQLi/XSS). 3) Missing authorization checks on endpoint handlers (Broken Object Level Authorization / BOLA).',
  },
];
