import { TechnicalQuestion } from '../../src/types';

export const DATASCIENCE_QUESTIONS: TechnicalQuestion[] = [
  // Level 1 — Basic (10 Questions)
  {
    question_id: 'ds_l1_q1',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Supervised vs Unsupervised',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between Supervised Learning and Unsupervised Learning?',
    expected_key_points: ['Supervised uses labeled training data with known targets (e.g. classification, regression)', 'Unsupervised discovers patterns/clusters in unlabeled data without targets (e.g. K-Means, PCA)'],
    improved_answer: 'Supervised learning trains models on labeled input-output pairs to predict target values. Unsupervised learning finds hidden patterns, groupings, or clusters in unlabeled data without predefined answers.',
  },
  {
    question_id: 'ds_l1_q2',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Classification vs Regression',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between a Classification problem and a Regression problem?',
    expected_key_points: ['Classification predicts categorical discrete labels (e.g. spam or not spam)', 'Regression predicts continuous numerical values (e.g. house price)'],
    improved_answer: 'Classification predicts discrete categories or classes (such as classifying an email as spam or not spam). Regression predicts continuous numeric quantities (such as predicting house prices or temperature).',
  },
  {
    question_id: 'ds_l1_q3',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Overfitting',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Overfitting in Machine Learning, and how do you prevent it?',
    expected_key_points: ['Model learns noise and memorizes training data, performing poorly on unseen test data', 'Prevent using cross-validation, regularization (L1/L2), pruning, or dropout', 'Collect more training data'],
    improved_answer: 'Overfitting occurs when a model memorizes the training data and noise rather than general patterns, performing poorly on unseen test data. It is prevented using regularization, cross-validation, and pruning.',
  },
  {
    question_id: 'ds_l1_q4',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Underfitting',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is Underfitting in Machine Learning, and how do you fix it?',
    expected_key_points: ['Model is too simple to capture underlying patterns in data', 'High bias resulting in poor performance on both training and test data', 'Fix by increasing model complexity, adding relevant features, or training longer'],
    improved_answer: 'Underfitting occurs when a model is too simple to learn the underlying trends in the data, resulting in high training error. It can be fixed by increasing model complexity or engineering more informative features.',
  },
  {
    question_id: 'ds_l1_q5',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Mean vs Median',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'When should you use the Median instead of the Mean to describe data?',
    expected_key_points: ['Mean is heavily distorted by extreme outliers or skewed distributions', 'Median is robust and resistant to outliers (e.g. income or house prices)', 'Median represents the 50th percentile midpoint'],
    improved_answer: 'Use the median when data contains extreme outliers or is heavily skewed (such as household income or real estate prices), because the mean is easily pulled by extreme values while the median remains stable.',
  },
  {
    question_id: 'ds_l1_q6',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Train/Validation/Test Splits',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the purpose of splitting data into Training, Validation, and Test sets?',
    expected_key_points: ['Training set: fits model weights', 'Validation set: tunes hyperparameters and prevents overfitting during development', 'Test set: unbiased evaluation of final model on unseen data'],
    improved_answer: 'The Training set fits the model parameters. The Validation set is used to tune hyperparameters and select the best model. The Test set is held out until the end to evaluate performance on completely unseen data.',
  },
  {
    question_id: 'ds_l1_q7',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Handling Missing Values',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What are common strategies for handling missing values in a dataset?',
    expected_key_points: ['Drop rows or columns with high missing rates', 'Impute with mean/median for numerical columns', 'Impute with mode or a "Missing" category for categorical columns'],
    improved_answer: 'Common approaches include: 1) Dropping rows or columns if the missing proportion is negligible or too large. 2) Imputing numerical columns using mean or median. 3) Imputing categorical columns using mode or a dedicated indicator.',
  },
  {
    question_id: 'ds_l1_q8',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Feature Scaling',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'Why is feature scaling (normalization or standardization) important for models like KNN, SVM, and Logistic Regression?',
    expected_key_points: ['Algorithms rely on Euclidean distances or gradient descent', 'Features with large numeric ranges dominate distance calculations', 'Scaling puts all features on an equal playing field (e.g. 0 to 1 or mean=0, std=1)'],
    improved_answer: 'Distance-based algorithms (like KNN and SVM) and gradient-based models are sensitive to feature scales. Without scaling, a feature measured in thousands (like salary) will dominate features measured in small numbers (like age).',
  },
  {
    question_id: 'ds_l1_q9',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Confusion Matrix',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a Confusion Matrix in classification?',
    expected_key_points: ['2x2 table showing True Positives (TP), True Negatives (TN), False Positives (FP), False Negatives (FN)', 'Evaluates classification model accuracy beyond simple overall percentage'],
    improved_answer: 'A Confusion Matrix is a summary table comparing actual target labels against predicted labels, breaking predictions down into True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN).',
  },
  {
    question_id: 'ds_l1_q10',
    domain: 'datascience',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Precision vs Recall',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between Precision and Recall?',
    expected_key_points: ['Precision: of all positive predictions, how many were actually positive? TP / (TP + FP)', 'Recall: of all actual positive cases, how many did the model detect? TP / (TP + FN)', 'Tradeoff between false alarms and missed detections'],
    improved_answer: 'Precision measures prediction purity: TP / (TP + FP)—minimizing false alarms. Recall measures detection completeness: TP / (TP + FN)—minimizing missed positives (critical in medical diagnoses and fraud).',
  },

  // Level 2 — Intermediate (10 Questions)
  {
    question_id: 'ds_l2_q1',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Bias-Variance Tradeoff',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'Explain the Bias-Variance tradeoff in Machine Learning.',
    expected_key_points: ['High bias leads to underfitting (model too simplistic)', 'High variance leads to overfitting (model too sensitive to training noise)', 'Optimal model balances bias and variance to minimize total test error'],
    improved_answer: 'Bias is error introduced by overly simplistic assumptions (underfitting). Variance is error from extreme sensitivity to fluctuations in the training set (overfitting). The goal is finding the balance that minimizes total error.',
  },
  {
    question_id: 'ds_l2_q2',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'P-Value in Statistics',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What does a p-value represent in hypothesis testing, and what does p < 0.05 mean?',
    expected_key_points: ['Probability of observing results at least as extreme assuming null hypothesis is true', 'p < 0.05 rejects null hypothesis at 5% significance level', 'Indicates observed effect is unlikely due to random chance'],
    improved_answer: 'A p-value is the probability of observing sample results at least as extreme as those measured, assuming the null hypothesis is true. A p-value < 0.05 allows us to reject the null hypothesis as statistically significant.',
  },
  {
    question_id: 'ds_l2_q3',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Decision Tree vs Random Forest',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'Why is a Random Forest generally better than a single Decision Tree?',
    expected_key_points: ['Single decision trees easily overfit with high variance', 'Random Forest is an ensemble of diverse trees trained on bootstrap samples with random feature subsets', 'Averaging predictions reduces variance without increasing bias'],
    improved_answer: 'A single decision tree has high variance and easily overfits. A Random Forest builds an ensemble of many decision trees using bootstrap aggregation (bagging) and random feature selection, significantly reducing variance.',
  },
  {
    question_id: 'ds_l2_q4',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'K-Fold Cross-Validation',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'How does K-Fold Cross-Validation work and why is it preferred over a single train-test split?',
    expected_key_points: ['Splits data into K equal folds', 'Trains on K-1 folds and evaluates on the remaining fold, repeating K times', 'Gives robust estimate of performance across all data points'],
    improved_answer: 'K-Fold cross-validation splits the dataset into K partitions. The model is trained on K-1 folds and tested on the remaining fold, rotating K times. Averaging the K test scores gives an unbiased metric unaffected by one lucky split.',
  },
  {
    question_id: 'ds_l2_q5',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Gradient Descent',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Gradient Descent and what happens if the learning rate is too high or too low?',
    expected_key_points: ['Iterative optimization algorithm to minimize loss function by taking steps in opposite direction of gradient', 'Too low: convergence is extremely slow and can get stuck in local minima', 'Too high: steps overshoot the minimum and diverge'],
    improved_answer: 'Gradient descent minimizes a model loss function by updating parameters in the direction of steepest descent. If the learning rate is too high, it overshoots and diverges; if too low, training takes too long to converge.',
  },
  {
    question_id: 'ds_l2_q6',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Bagging vs Boosting',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the main difference between Bagging and Boosting?',
    expected_key_points: ['Bagging (e.g. Random Forest) trains models in parallel independently to reduce variance', 'Boosting (e.g. XGBoost, AdaBoost) trains models sequentially, each correcting errors of previous models to reduce bias'],
    improved_answer: 'Bagging trains multiple base models independently in parallel on bootstrap samples to reduce variance. Boosting builds models sequentially, with each new model focusing on correcting errors made by previous iterations to reduce bias.',
  },
  {
    question_id: 'ds_l2_q7',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Logistic vs Linear Regression',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'Why can you not use standard Linear Regression directly for binary classification?',
    expected_key_points: ['Linear regression outputs unbounded continuous values from -infinity to +infinity', 'Probabilities must be bounded between 0 and 1', 'Logistic regression uses sigmoid function to map predictions to valid probabilities'],
    improved_answer: 'Linear regression outputs unbounded continuous numbers which can exceed [0, 1]. Logistic regression passes linear equations through a sigmoid activation function, constraining outputs between 0 and 1 as valid probabilities.',
  },
  {
    question_id: 'ds_l2_q8',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'ROC-AUC Curve',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the ROC-AUC score and why is it preferred over accuracy on imbalanced datasets?',
    expected_key_points: ['Plots True Positive Rate against False Positive Rate across all decision thresholds', 'AUC score of 1.0 is perfect; 0.5 is random guessing', 'Accuracy is misleading when 99% of samples belong to one class'],
    improved_answer: 'The ROC curve plots True Positive Rate vs False Positive Rate across all classification thresholds. The Area Under the Curve (AUC) measures the model ability to rank positives above negatives regardless of threshold or class imbalance.',
  },
  {
    question_id: 'ds_l2_q9',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'PCA Dimensionality Reduction',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Principal Component Analysis (PCA) and why is it used?',
    expected_key_points: ['Unsupervised linear dimensionality reduction technique', 'Finds orthogonal principal component axes that maximize variance', 'Compresses high-dimensional feature spaces and reduces multicollinearity'],
    improved_answer: 'PCA transforms high-dimensional correlated features into a smaller set of linearly uncorrelated components that capture the maximum variance in the data, speeding up training and preventing the curse of dimensionality.',
  },
  {
    question_id: 'ds_l2_q10',
    domain: 'datascience',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Data Leakage',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is Data Leakage in machine learning and how do you prevent it during preprocessing?',
    expected_key_points: ['Information from outside the training dataset used to train the model', 'Example: computing mean/scaling on entire dataset before train-test split', 'Prevent by fitting scalers and encoders ONLY on training data'],
    improved_answer: 'Data leakage happens when information from test data contaminates the training phase. To prevent it, always perform train-test splitting first, and fit imputation and scaling transformers strictly on the training set alone.',
  },

  // Level 3 — Practical & Coding (10 Questions)
  {
    question_id: 'ds_l3_q1',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Mean and Median Function',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a JavaScript function to compute the mean and median of an array of numbers.',
    code_template: `function getMeanAndMedian(numbers) {
  // Return { mean, median }
}`,
    expected_key_points: ['Sum numbers and divide by length for mean', 'Sort numbers to find middle element(s) for median', 'Handle even vs odd length'],
    improved_answer: `function getMeanAndMedian(numbers) {
  if (!numbers.length) return { mean: 0, median: 0 };
  const sum = numbers.reduce((acc, val) => acc + val, 0);
  const mean = sum / numbers.length;
  const sorted = [...numbers].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  const median = sorted.length % 2 !== 0 
    ? sorted[mid] 
    : (sorted[mid - 1] + sorted[mid]) / 2;
  return { mean, median };
}`,
  },
  {
    question_id: 'ds_l3_q2',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Confusion Matrix Metrics',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a function that calculates Precision, Recall, and F1-Score given TP, FP, and FN.',
    code_template: `function calculateMetrics(tp, fp, fn) {
  // Return { precision, recall, f1 }
}`,
    expected_key_points: ['Precision = tp / (tp + fp)', 'Recall = tp / (tp + fn)', 'F1 = 2 * (precision * recall) / (precision + recall)', 'Handle division by zero'],
    improved_answer: `function calculateMetrics(tp, fp, fn) {
  const precision = (tp + fp) === 0 ? 0 : tp / (tp + fp);
  const recall = (tp + fn) === 0 ? 0 : tp / (tp + fn);
  const f1 = (precision + recall) === 0 ? 0 : 2 * (precision * recall) / (precision + recall);
  return { precision, recall, f1 };
}`,
  },
  {
    question_id: 'ds_l3_q3',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Accuracy Paradox in Fraud Detection',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'A credit card fraud model achieves 99.8% accuracy, but business teams say it is useless. Why?',
    expected_key_points: ['Severe class imbalance (e.g. only 0.1% transactions are fraudulent)', 'A dumb model predicting "never fraud" gets 99.9% accuracy with 0 recall', 'Model fails to detect actual fraudulent transactions'],
    improved_answer: 'Because fraudulent transactions represent only 0.2% of the dataset, a dummy model predicting "not fraud" for every transaction achieves 99.8% accuracy while catching zero fraud cases. Precision, Recall, and PR-AUC must be used instead.',
  },
  {
    question_id: 'ds_l3_q4',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Handling Imbalanced Data',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What are three practical techniques to train a classifier on heavily imbalanced data?',
    expected_key_points: ['Resampling: SMOTE oversampling minority class or undersampling majority', 'Class weighting / loss penalty (class_weight="balanced")', 'Threshold tuning on predicted probability distribution'],
    improved_answer: '1) Synthetic oversampling (SMOTE) or downsampling the majority class. 2) Adding class-weighted loss penalties to penalize minority misclassifications. 3) Adjusting the classification decision threshold instead of using default 0.5.',
  },
  {
    question_id: 'ds_l3_q5',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Outlier Detection',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do you identify outliers in a numerical column, and when should you remove them versus cap them?',
    expected_key_points: ['Use IQR (Interquartile Range) method (1.5 * IQR) or Z-score > 3', 'Remove only if confirmed data entry error or corruption', 'Cap/Winsorize if outliers are legitimate extreme real-world values'],
    improved_answer: 'Use the IQR rule (values outside Q1 - 1.5*IQR or Q3 + 1.5*IQR). Remove values if they are clear data entry mistakes. If they are valid extreme observations (e.g. high-value purchases), cap them (Winsorization) or use tree models robust to outliers.',
  },
  {
    question_id: 'ds_l3_q6',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Feature Selection with Many Columns',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'If a dataset has 300 feature columns and only 1,000 rows, how do you select the best features to prevent overfitting?',
    expected_key_points: ['Remove low-variance and highly correlated collinear features', 'Use tree feature importances (Random Forest or XGBoost)', 'Apply L1 Lasso regularization which drives irrelevant coefficients to zero'],
    improved_answer: '1) Drop zero-variance columns and remove highly correlated redundant features (correlation > 0.85). 2) Use L1 (Lasso) regularization to shrink non-essential weights to zero. 3) Select top features based on tree feature importance scores.',
  },
  {
    question_id: 'ds_l3_q7',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Model Drift in Production',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'What is Concept Drift versus Data Drift, and how do you monitor for it after deploying a model?',
    expected_key_points: ['Data drift: input feature distributions shift over time (P(X) changes)', 'Concept drift: relationship between features and target changes (P(Y|X) changes)', 'Monitor distribution tests (KS-test, PSI) and tracking production performance metrics'],
    improved_answer: 'Data drift means incoming user input distributions change (e.g. customer demographics change). Concept drift means the underlying relationship between inputs and outputs changes (e.g. shopping habits change after a crisis). Monitor using Population Stability Index (PSI) and retraining schedules.',
  },
  {
    question_id: 'ds_l3_q8',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Explaining Black-Box Models (SHAP)',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do SHAP (Shapley Additive exPlanations) values help explain predictions from a complex model to non-technical stakeholders?',
    expected_key_points: ['Based on cooperative game theory', 'Measures fair contribution of each feature to the difference between actual prediction and base rate', 'Provides clear feature impact direction (+ or -) per prediction'],
    improved_answer: 'SHAP values break down a specific prediction into contributions from each feature. Stakeholders can clearly see that a loan application was rejected because feature "Debt-to-Income" contributed +35% toward rejection, providing transparent explanations.',
  },
  {
    question_id: 'ds_l3_q9',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'End-to-End Churn Pipeline',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'Outline the main stages of building an end-to-end Machine Learning pipeline to predict customer churn.',
    expected_key_points: ['Data collection and exploratory data analysis (EDA)', 'Preprocessing (imputation, encoding, scaling)', 'Model training, hyperparameter tuning, and cross-validation', 'Deployment via REST API with live drift monitoring'],
    improved_answer: '1) Data ingestion and EDA to understand churn patterns. 2) Preprocessing pipeline (handling missing values, one-hot encoding). 3) Train and tune ensemble models (XGBoost) using cross-validation. 4) Deploy inference API with drift tracking.',
  },
  {
    question_id: 'ds_l3_q10',
    domain: 'datascience',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'One-Hot vs Label Encoding',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'When should you use One-Hot Encoding versus Label/Ordinal Encoding for categorical features?',
    expected_key_points: ['Ordinal encoding when categories have intrinsic mathematical order (e.g. Low, Medium, High)', 'One-hot encoding for nominal categories without ranking (e.g. Red, Blue, Green)', 'Avoid one-hot on high cardinality columns (e.g. Zip codes) to prevent dimensional explosion'],
    improved_answer: 'Use Ordinal Encoding when categories have natural order (e.g., Small, Medium, Large) so numbers reflect rank. Use One-Hot Encoding for unordered nominal categories (e.g., City) to prevent models from assuming false numerical hierarchies.',
  },
];
