import { TechnicalQuestion } from '../../src/types';

export const FULLSTACK_QUESTIONS: TechnicalQuestion[] = [
  // Level 1 — Basic (10 Questions)
  {
    question_id: 'fs_l1_q1',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'JavaScript Variables',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between var, let, and const in JavaScript?',
    expected_key_points: ['var is function-scoped', 'let and const are block-scoped', 'const cannot be reassigned'],
    improved_answer: 'var is function-scoped and hoisted with undefined. let and const are block-scoped with a temporal dead zone. const creates an immutable binding that cannot be reassigned.',
  },
  {
    question_id: 'fs_l1_q2',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'DOM Basics',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the DOM in web development and how does the browser use it?',
    expected_key_points: ['Document Object Model tree representation of HTML', 'Allows JavaScript to read and update page structure', 'Browser renders HTML into DOM elements'],
    improved_answer: 'The Document Object Model (DOM) is a tree-like representation of HTML elements in memory. The browser parses HTML into the DOM, allowing JavaScript to dynamically access, modify, and style elements.',
  },
  {
    question_id: 'fs_l1_q3',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'HTTP Methods',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between HTTP GET and POST requests?',
    expected_key_points: ['GET requests data from a server without modifying it', 'POST sends data in request body to create or update resources', 'GET parameters appear in URL query string while POST is in body'],
    improved_answer: 'GET is used to retrieve data from a server, with parameters sent in the URL. POST is used to send data in the request body to create or update a resource on the server.',
  },
  {
    question_id: 'fs_l1_q4',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'JavaScript Equality',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between == and === in JavaScript?',
    expected_key_points: ['== performs type coercion before comparison', '=== is strict equality checking both value and type without coercion'],
    improved_answer: '== is loose equality that converts types before comparing. === is strict equality that requires both the value and the data type to match without coercion.',
  },
  {
    question_id: 'fs_l1_q5',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'React Props vs State',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between props and state in React?',
    expected_key_points: ['Props are read-only inputs passed from parent to child', 'State is local mutable data managed inside the component', 'Changes to props or state trigger re-render'],
    improved_answer: 'Props are read-only arguments passed from parent to child components. State is local, mutable data managed within the component using hooks like useState.',
  },
  {
    question_id: 'fs_l1_q6',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'CSS Box Model',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the CSS Box Model and what are its four parts?',
    expected_key_points: ['Content, Padding, Border, Margin', 'Padding is inside border, Margin is outside border', 'box-sizing border-box includes padding and border in width'],
    improved_answer: 'The CSS Box Model consists of four concentric areas: Content (the text or image), Padding (inner space), Border (boundary line), and Margin (outer clearance around the element).',
  },
  {
    question_id: 'fs_l1_q7',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'JavaScript Closures',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is a closure in JavaScript, and when is it useful?',
    expected_key_points: ['Function bundled with its lexical environment', 'Inner function remembers variables from outer scope even after outer returns', 'Used for data privacy and callbacks'],
    improved_answer: 'A closure is a function that retains access to variables from its outer lexical scope even after that outer function has finished executing. It is commonly used for data privacy and factory functions.',
  },
  {
    question_id: 'fs_l1_q8',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Asynchronous JavaScript',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between synchronous and asynchronous code in JavaScript?',
    expected_key_points: ['Synchronous code blocks execution until each line completes', 'Asynchronous code runs in background (Promises, async/await) without freezing UI'],
    improved_answer: 'Synchronous code executes line-by-line, blocking the next operation until the current one finishes. Asynchronous code allows time-consuming tasks (like API calls) to run in the background without freezing the UI.',
  },
  {
    question_id: 'fs_l1_q9',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'HTTP Status Codes',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What do HTTP status codes 200, 400, 404, and 500 mean?',
    expected_key_points: ['200 OK: success', '400 Bad Request: client sent invalid data', '404 Not Found: resource does not exist', '500 Internal Server Error: server crashed or failed'],
    improved_answer: '200 means success. 400 means Bad Request due to invalid client input. 404 means Not Found because the URL does not exist. 500 means Internal Server Error due to an unhandled exception on the server.',
  },
  {
    question_id: 'fs_l1_q10',
    domain: 'fullstack',
    level: 1,
    level_name: 'Level 1 — Basic',
    topic: 'Browser Storage',
    difficulty: 'Easy',
    type: 'conceptual',
    question: 'What is the difference between localStorage, sessionStorage, and cookies?',
    expected_key_points: ['localStorage persists until manually cleared (~5-10MB)', 'sessionStorage is cleared when the tab closes', 'cookies are sent with every HTTP request (~4KB)'],
    improved_answer: 'localStorage persists until explicitly cleared. sessionStorage lasts only while the browser tab is open. Cookies have a smaller 4KB limit and are automatically sent to the server with every HTTP request.',
  },

  // Level 2 — Intermediate (10 Questions)
  {
    question_id: 'fs_l2_q1',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'React Virtual DOM',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the Virtual DOM in React and why is it faster than directly updating the real DOM?',
    expected_key_points: ['Lightweight JavaScript representation of real DOM', 'React diffs changes in memory', 'Only applies batch minimal updates to real DOM'],
    improved_answer: 'The Virtual DOM is an in-memory representation of the actual DOM. When state changes, React compares the new Virtual DOM with the previous snapshot (diffing) and updates only the altered nodes in the real DOM.',
  },
  {
    question_id: 'fs_l2_q2',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'JavaScript Event Loop',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'How does the JavaScript Event Loop handle microtasks (Promises) versus macrotasks (setTimeout)?',
    expected_key_points: ['Call stack executes synchronous code first', 'Microtask queue (Promises) empties completely before macrotasks', 'Macrotask queue (setTimeout, setInterval) runs one task at a time'],
    improved_answer: 'Synchronous code runs on the call stack first. Once cleared, the Event Loop flushes the entire microtask queue (Promise callbacks) before picking the next macrotask (such as setTimeout) from the task queue.',
  },
  {
    question_id: 'fs_l2_q3',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'CORS',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is CORS (Cross-Origin Resource Sharing) and why does the browser block cross-origin requests?',
    expected_key_points: ['Browser security feature enforcing same-origin policy', 'Blocks scripts on one domain from accessing data on another without permission', 'Server sends Access-Control-Allow-Origin header to permit requests'],
    improved_answer: 'CORS is a browser security mechanism that prevents malicious websites from reading data from another origin without authorization. The target server must explicitly send Access-Control-Allow-Origin headers.',
  },
  {
    question_id: 'fs_l2_q4',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'SQL vs NoSQL',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the main difference between SQL (relational) and NoSQL databases?',
    expected_key_points: ['SQL uses structured schemas, tables, and ACID transactions', 'NoSQL uses flexible documents/key-values and scales horizontally', 'SQL is great for complex relations; NoSQL for dynamic unstructured data'],
    improved_answer: 'SQL databases are relational, table-based, and enforce rigid schemas with ACID transactions (e.g. PostgreSQL). NoSQL databases (e.g. MongoDB) store unstructured or document-based data and scale out horizontally.',
  },
  {
    question_id: 'fs_l2_q5',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'React useEffect Hook',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'How does the dependency array in React useEffect work?',
    expected_key_points: ['No array: runs after every render', 'Empty array []: runs only once on mount', 'With dependencies [a, b]: runs when any dependency changes', 'Optional cleanup function runs before next effect or on unmount'],
    improved_answer: 'If no dependency array is passed, useEffect runs on every render. An empty array [] runs once on mount. Supplying variables [a, b] triggers the effect only when those values change between renders.',
  },
  {
    question_id: 'fs_l2_q6',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'JWT Authentication',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a JSON Web Token (JWT) and what are its three parts?',
    expected_key_points: ['Header, Payload, Signature', 'Base64Url encoded string separated by dots', 'Stateless authentication token verified using secret or public key'],
    improved_answer: 'A JWT is a compact, URL-safe token with three dot-separated parts: Header (algorithm), Payload (claims/user data), and Signature (cryptographic verification string ensuring the token has not been tampered with).',
  },
  {
    question_id: 'fs_l2_q7',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'REST vs GraphQL',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the key difference between REST and GraphQL APIs?',
    expected_key_points: ['REST has multiple fixed endpoints returning fixed data structures', 'GraphQL has a single endpoint where clients request exact fields needed', 'GraphQL prevents over-fetching and under-fetching'],
    improved_answer: 'REST relies on multiple endpoints with fixed response structures. GraphQL exposes a single endpoint where clients query specifically the fields they need, eliminating over-fetching and multiple network round-trips.',
  },
  {
    question_id: 'fs_l2_q8',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'Database Indexing',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is a database index and how does it speed up queries?',
    expected_key_points: ['Data structure (often B-tree) pointing to table rows', 'Avoids scanning the entire table (full table scan)', 'Speeds up SELECT queries but slightly slows down INSERT/UPDATE writes'],
    improved_answer: 'A database index is a specialized lookup data structure (typically a B-tree) that allows the database engine to locate matching rows quickly without scanning the entire table, trading write speed for faster reads.',
  },
  {
    question_id: 'fs_l2_q9',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'WebSockets vs HTTP',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between WebSockets and standard HTTP requests?',
    expected_key_points: ['HTTP is request-response and unidirectional', 'WebSocket is a persistent full-duplex bidirectional connection', 'WebSockets are ideal for live chat, real-time dashboards, and multiplayer'],
    improved_answer: 'HTTP is a stateless request-response protocol where each exchange requires a request from the client. WebSockets provide a persistent, two-way connection allowing server and client to send messages in real-time.',
  },
  {
    question_id: 'fs_l2_q10',
    domain: 'fullstack',
    level: 2,
    level_name: 'Level 2 — Intermediate',
    topic: 'SSR vs CSR',
    difficulty: 'Medium',
    type: 'conceptual',
    question: 'What is the difference between Server-Side Rendering (SSR) and Client-Side Rendering (CSR)?',
    expected_key_points: ['SSR generates HTML on server per request for faster initial load and SEO', 'CSR sends minimal HTML and renders UI in browser using JavaScript', 'SSR is better for SEO; CSR provides smooth page transitions once loaded'],
    improved_answer: 'In CSR, the browser downloads a blank HTML shell and builds the UI using JavaScript. In SSR, the server renders the complete HTML on each request, offering superior SEO and faster first contentful paint.',
  },

  // Level 3 — Practical & Coding (10 Questions)
  {
    question_id: 'fs_l3_q1',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'String Reversal',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a JavaScript function to reverse a string without using the built-in .reverse() method.',
    code_template: `function reverseString(str) {
  // Return reversed string without str.split('').reverse().join('')
}`,
    expected_key_points: ['Loop backwards or use reduce/two-pointer approach', 'Handle empty string', 'Return new reversed string'],
    improved_answer: `function reverseString(str) {
  let reversed = '';
  for (let i = str.length - 1; i >= 0; i--) {
    reversed += str[i];
  }
  return reversed;
}`,
  },
  {
    question_id: 'fs_l3_q2',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Palindrome Check',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a function to check if a string is a palindrome (reads the same backward as forward).',
    code_template: `function isPalindrome(str) {
  // Return true if str is a palindrome, false otherwise
}`,
    expected_key_points: ['Compare characters from start and end moving inwards', 'Case insensitive / strip punctuation if needed', 'Return boolean'],
    improved_answer: `function isPalindrome(str) {
  const clean = str.toLowerCase().replace(/[^a-z0-9]/g, '');
  let left = 0;
  let right = clean.length - 1;
  while (left < right) {
    if (clean[left] !== clean[right]) return false;
    left++;
    right--;
  }
  return true;
}`,
  },
  {
    question_id: 'fs_l3_q3',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Array Deduplication',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a function to remove duplicate numbers from an array in JavaScript.',
    code_template: `function removeDuplicates(arr) {
  // Return array with only unique elements
}`,
    expected_key_points: ['Use Set: [...new Set(arr)] or filter with indexOf', 'Preserve single copy of each element', 'O(n) time complexity'],
    improved_answer: `function removeDuplicates(arr) {
  return Array.from(new Set(arr));
}`,
  },
  {
    question_id: 'fs_l3_q4',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Debounce Function',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Implement a simple debounce function in JavaScript.',
    code_template: `function debounce(fn, delay) {
  // Return debounced version of fn
}`,
    expected_key_points: ['Maintain timer reference in closure', 'Clear previous timer using clearTimeout', 'Set new timer with setTimeout'],
    improved_answer: `function debounce(fn, delay) {
  let timer;
  return function (...args) {
    clearTimeout(timer);
    timer = setTimeout(() => fn.apply(this, args), delay);
  };
}`,
  },
  {
    question_id: 'fs_l3_q5',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Find Maximum',
    difficulty: 'Hard',
    type: 'coding',
    language: 'javascript',
    question: 'Write a function that finds the largest number in an array of numbers.',
    code_template: `function findMax(arr) {
  // Return maximum number in arr
}`,
    expected_key_points: ['Handle empty array edge case', 'Iterate through array or use Math.max with spread', 'Return maximum value'],
    improved_answer: `function findMax(arr) {
  if (!arr || arr.length === 0) return null;
  let max = arr[0];
  for (let i = 1; i < arr.length; i++) {
    if (arr[i] > max) max = arr[i];
  }
  return max;
}`,
  },
  {
    question_id: 'fs_l3_q6',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'SQL Injection Prevention',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How do you prevent SQL injection in a full stack web application?',
    expected_key_points: ['Use parameterized queries or prepared statements', 'Never concatenate raw user input into SQL strings', 'Use an ORM like Prisma or Sequelize', 'Validate and sanitize input'],
    improved_answer: 'The primary defense against SQL injection is using parameterized queries or prepared statements, ensuring user input is treated strictly as data rather than executable SQL commands.',
  },
  {
    question_id: 'fs_l3_q7',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'React Infinite Loop Bug',
    difficulty: 'Hard',
    type: 'debugging',
    question: 'Why does calling a state setter function directly inside a React component body cause an infinite loop?',
    expected_key_points: ['Setting state triggers a re-render', 'Component function executes again during re-render', 'Calls state setter again, causing an infinite loop', 'Fix by moving inside useEffect or event handler'],
    improved_answer: 'Calling setState directly inside the component body executes during every render. Updating state schedules a re-render, which calls setState again, creating an immediate infinite render loop. State updates must be placed inside event handlers or useEffect hooks.',
  },
  {
    question_id: 'fs_l3_q8',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Website Speed Optimization',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'If a web application is taking 5 seconds to load, what are the top 3 things you would inspect and optimize?',
    expected_key_points: ['Optimize large uncompressed images and assets with lazy loading', 'Analyze large JavaScript bundle sizes using code splitting', 'Check backend API response latency and database queries with caching'],
    improved_answer: '1) Compress and lazy-load heavy images. 2) Implement code-splitting to reduce the initial JavaScript bundle. 3) Cache expensive API responses and optimize database queries to reduce server response time.',
  },
  {
    question_id: 'fs_l3_q9',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'Secure Token Storage',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'Where is the safest place to store an authentication token in a Single Page Application (SPA), and why?',
    expected_key_points: ['HttpOnly, Secure, SameSite cookie', 'Prevents client-side JavaScript access (protects against XSS)', 'LocalStorage is accessible by any script and vulnerable to XSS'],
    improved_answer: 'An HttpOnly, Secure, SameSite cookie is the safest place because browser JavaScript cannot access it, shielding the token from theft via Cross-Site Scripting (XSS) attacks.',
  },
  {
    question_id: 'fs_l3_q10',
    domain: 'fullstack',
    level: 3,
    level_name: 'Level 3 — Practical',
    topic: 'API Rate Limiting',
    difficulty: 'Hard',
    type: 'scenario',
    question: 'How does API rate limiting work and why is it used on public endpoints?',
    expected_key_points: ['Limits number of requests a user or IP can make in a time window', 'Returns HTTP 429 Too Many Requests when limit is exceeded', 'Protects against DDoS, brute-force attacks, and server overload'],
    improved_answer: 'API rate limiting restricts how many requests a client IP or user can submit within a timeframe (e.g. 100 requests per minute). When exceeded, the server returns status 429 Too Many Requests, preventing abuse and server crashes.',
  },
];
