import { AptitudeQuestion } from '../../src/types';

export function getSpecializedQuestions(): AptitudeQuestion[] {
  const list: AptitudeQuestion[] = [];
  let counter = 0;

  const addQ = (
    level_id: number,
    category: string,
    difficulty: 'Easy' | 'Medium' | 'Hard',
    question: string,
    correctText: string,
    d1: string,
    d2: string,
    d3: string,
    exp: string
  ) => {
    counter++;
    const posIndex = (counter - 1) % 4;
    const letters: Array<'A' | 'B' | 'C' | 'D'> = ['A', 'B', 'C', 'D'];
    const correctLetter = letters[posIndex];

    const distractors = [d1, d2, d3];
    if (counter % 2 === 1) {
      const tmp = distractors[0];
      distractors[0] = distractors[1];
      distractors[1] = tmp;
    }

    const opts: Record<'A' | 'B' | 'C' | 'D', string> = { A: '', B: '', C: '', D: '' };
    opts[correctLetter] = correctText;

    let distIdx = 0;
    for (const l of letters) {
      if (l !== correctLetter) {
        opts[l] = distractors[distIdx++] || '';
      }
    }

    list.push({
      question_id: `q_spec_l${level_id}_${counter}`,
      topic_id: 'specialized',
      level_id,
      category,
      concept: category,
      difficulty,
      question,
      option_a: opts.A,
      option_b: opts.B,
      option_c: opts.C,
      option_d: opts.D,
      correct_answer: correctLetter,
      explanation: exp,
      pool_type: 'learning',
    });
  };

  // Level 1: Data Structures (30 distinct questions)
  const dsData = [
    { q: 'Which data structure follows the LIFO (Last In First Out) principle?', ans: 'Stack', d1: 'Queue', d2: 'Heap', d3: 'Linked List', exp: 'A Stack processes items in Last-In-First-Out order.' },
    { q: 'Which data structure operates on a FIFO (First In First Out) basis?', ans: 'Queue', d1: 'Stack', d2: 'Binary Tree', d3: 'Hash Table', exp: 'A Queue adheres strictly to First-In-First-Out processing.' },
    { q: 'What is the time complexity of searching an element in a balanced Binary Search Tree (BST)?', ans: 'O(log N)', d1: 'O(1)', d2: 'O(N)', d3: 'O(N^2)', exp: 'A balanced BST eliminates half the remaining nodes at each step, yielding O(log N).' },
    { q: 'Which data structure provides O(1) average time complexity for key lookups and insertions?', ans: 'Hash Table', d1: 'Array List', d2: 'Singly Linked List', d3: 'Trie', exp: 'Hash Tables compute bucket indices in O(1) average time.' },
    { q: 'In a singly linked list, what is the time complexity to insert a new node at the head (beginning)?', ans: 'O(1)', d1: 'O(N)', d2: 'O(log N)', d3: 'O(N log N)', exp: 'Prepending a node requires updating only the head pointer, taking constant O(1) time.' },
    { q: 'Which data structure is most optimal for implementing a priority queue?', ans: 'Binary Heap', d1: 'Stack', d2: 'Circular Queue', d3: 'Adjacency Matrix', exp: 'Binary Heaps offer O(1) peek and O(log N) insertion/extraction for priorities.' },
    { q: 'What is the minimum number of queues needed to implement a Stack?', ans: '2 queues', d1: '1 queue', d2: '3 queues', d3: '4 queues', exp: 'Two FIFO queues can emulate a LIFO stack by transferring elements.' },
    { q: 'Which self-balancing binary search tree guarantees that no path is more than twice as long as any other?', ans: 'Red-Black Tree', d1: 'B-Tree', d2: 'Splay Tree', d3: 'Ternary Tree', exp: 'Red-Black tree coloring invariants bound the maximum height to 2 * log2(N + 1).' },
    { q: 'In a complete binary tree of height H with N nodes, what is the relationship between height and node count?', ans: 'H = floor(log2(N))', d1: 'H = N / 2', d2: 'H = N^2', d3: 'H = sqrt(N)', exp: 'The height of a complete binary tree is logarithmic with respect to total nodes.' },
    { q: 'Which tree traversal visits the left subtree, root node, and then right subtree?', ans: 'In-order Traversal', d1: 'Pre-order Traversal', d2: 'Post-order Traversal', d3: 'Level-order Traversal', exp: 'In-order traversal visits nodes in (Left, Root, Right) order.' },
    { q: 'In an array of size N, what is the time complexity of accessing an element at index i directly?', ans: 'O(1)', d1: 'O(N)', d2: 'O(log N)', d3: 'O(i)', exp: 'Contiguous memory addressing allows instant O(1) random access.' },
    { q: 'Which tree structure is optimized for storing hierarchical routing prefixes and autocomplete dictionary words?', ans: 'Trie (Prefix Tree)', d1: 'AVL Tree', d2: 'Segment Tree', d3: 'Fenwick Tree', exp: 'Tries store shared string prefixes along common tree edges.' },
    { q: 'What is the space complexity of an Adjacency Matrix representing a graph with V vertices?', ans: 'O(V^2)', d1: 'O(V + E)', d2: 'O(E^2)', d3: 'O(V log V)', exp: 'A 2D array of dimensions V x V requires O(V^2) memory.' },
    { q: 'Which data structure is used to implement Breadth-First Search (BFS) graph traversal?', ans: 'Queue', d1: 'Stack', d2: 'Priority Queue', d3: 'Hash Set', exp: 'BFS explores vertices level by level using a FIFO Queue.' },
    { q: 'Which data structure is typically used for Depth-First Search (DFS) graph traversal?', ans: 'Stack (or Call Stack Recursion)', d1: 'Queue', d2: 'Min-Heap', d3: 'Circular Buffer', exp: 'DFS dives along paths using a LIFO Stack or recursive function frames.' },
    { q: 'In a circular queue of capacity K with front and rear pointers, how is the next index computed?', ans: '(index + 1) % K', d1: 'index + 1', d2: '(index * 2) % K', d3: 'index - 1', exp: 'Modulo arithmetic wraps the pointer around the fixed array boundary.' },
    { q: 'What is the balance factor constraint in an AVL Tree for every node?', ans: '|Height(Left) - Height(Right)| <= 1', d1: '|Height(Left) - Height(Right)| <= 2', d2: 'Height(Left) == Height(Right)', d3: 'Height(Left) > Height(Right)', exp: 'AVL invariant strictly restricts height difference of subtrees to -1, 0, or +1.' },
    { q: 'Which data structure is optimal for finding range sum queries with point updates in O(log N)?', ans: 'Fenwick Tree (Binary Indexed Tree) or Segment Tree', d1: 'Doubly Linked List', d2: 'Stack', d3: 'Hash Table', exp: 'Binary Indexed Trees and Segment Trees support O(log N) prefix sums and point updates.' },
    { q: 'What is the worst-case time complexity of inserting into an unbalanced Binary Search Tree?', ans: 'O(N)', d1: 'O(log N)', d2: 'O(1)', d3: 'O(N log N)', exp: 'When items are inserted in sorted order, an unbalanced BST degrades into a linked list of height N.' },
    { q: 'Which structure enables finding if two items belong to the same set and merging sets in nearly O(1)?', ans: 'Disjoint Set Union (Union-Find)', d1: 'B-Tree', d2: 'Trie', d3: 'Skip List', exp: 'Union-Find with path compression and rank union runs in inverse Ackermann time O(alpha(N)).' },
    { q: 'In a Max-Heap, where is the largest key always located?', ans: 'At the root node', d1: 'At the leftmost leaf', d2: 'At the rightmost leaf', d3: 'In the middle level', exp: 'The max-heap property mandates that every parent key is greater than or equal to its children.' },
    { q: 'What is the number of edges in a connected undirected tree with N vertices?', ans: 'N - 1', d1: 'N', d2: 'N + 1', d3: '2N', exp: 'Any tree with N vertices has exactly N - 1 edges and contains no cycles.' },
    { q: 'Which linked list allows traversal in both forward and backward directions?', ans: 'Doubly Linked List', d1: 'Singly Linked List', d2: 'Circular Singly Linked List', d3: 'Unrolled Linked List', exp: 'Doubly linked lists store both `next` and `prev` pointers.' },
    { q: 'In a Hash Table with open addressing, what method checks the sequence (hash + i^2) % size during collisions?', ans: 'Quadratic Probing', d1: 'Linear Probing', d2: 'Double Hashing', d3: 'Separate Chaining', exp: 'Quadratic probing offsets bucket collisions by squared increments i^2.' },
    { q: 'What is the maximum number of children a node can have in a binary tree?', ans: '2', d1: '1', d2: '3', d3: 'Unlimited', exp: 'By definition, binary tree nodes have at most two child nodes (left and right).' },
    { q: 'Which data structure can be used to efficiently evaluate postfix mathematical expressions?', ans: 'Stack', d1: 'Queue', d2: 'Heap', d3: 'Binary Tree', exp: 'Operands are pushed onto a stack and popped when operators are encountered.' },
    { q: 'What is the time complexity of deleting a node from a Doubly Linked List when given a direct pointer to that node?', ans: 'O(1)', d1: 'O(N)', d2: 'O(log N)', d3: 'O(N^2)', exp: 'With direct reference, updating neighbor pointers takes constant O(1) time.' },
    { q: 'Which data structure uses probabilistic layers of linked lists to achieve O(log N) search and insertion?', ans: 'Skip List', d1: 'B-Tree', d2: 'Hash Map', d3: 'Array', exp: 'Skip lists create express lanes across layered linked nodes with geometric coin flips.' },
    { q: 'In a 2D array matrix of size R rows and C columns in row-major order, what is the offset formula for cell (i, j)?', ans: 'i * C + j', d1: 'j * R + i', d2: 'i + j', d3: 'i * R + j', exp: 'Row-major layout strides by row index multiplied by total columns C plus column offset j.' },
    { q: 'What is the leaf node count in a strictly full binary tree with I internal nodes?', ans: 'I + 1', d1: '2 * I', d2: 'I - 1', d3: '2^I', exp: 'In a full binary tree where every internal node has 2 children, Leaves = Internal Nodes + 1.' },
  ];
  dsData.forEach((d) => {
    addQ(1, 'Data Structures', 'Medium', d.q, d.ans, d.d1, d.d2, d.d3, d.exp);
  });

  // Level 2: Algorithms & Complexity (30 distinct questions)
  const algoData = [
    { q: 'What is the average time complexity of QuickSort?', ans: 'O(N log N)', d1: 'O(N^2)', d2: 'O(N)', d3: 'O(log N)', exp: 'QuickSort splits partitions in half on average, leading to O(N log N).' },
    { q: 'What is the worst-case time complexity of QuickSort when bad pivot selection occurs?', ans: 'O(N^2)', d1: 'O(N log N)', d2: 'O(N)', d3: 'O(2^N)', exp: 'Unbalanced partitions (e.g. already sorted array with first element pivot) cause O(N^2).' },
    { q: 'What is the guaranteed worst-case time complexity of MergeSort?', ans: 'O(N log N)', d1: 'O(N^2)', d2: 'O(N)', d3: 'O(log N)', exp: 'MergeSort divides and merges arrays deterministically in O(N log N) time in all cases.' },
    { q: 'Which algorithm finds the single-source shortest path in a graph with non-negative edge weights?', ans: 'Dijkstra\'s Algorithm', d1: 'Kruskal\'s Algorithm', d2: 'Prim\'s Algorithm', d3: 'Floyd-Warshall Algorithm', exp: 'Dijkstra uses a min-priority queue to find shortest paths with non-negative weights.' },
    { q: 'Which algorithm can find shortest paths in graphs that contain negative edge weights (and detect negative cycles)?', ans: 'Bellman-Ford Algorithm', d1: 'Dijkstra\'s Algorithm', d2: 'Prim\'s Algorithm', d3: 'Binary Search', exp: 'Bellman-Ford relaxes all E edges V-1 times, safely handling negative weights.' },
    { q: 'Which algorithm computes all-pairs shortest paths in O(V^3) time complexity?', ans: 'Floyd-Warshall Algorithm', d1: 'Dijkstra\'s Algorithm', d2: 'Kruskal\'s Algorithm', d3: 'Topological Sort', exp: 'Floyd-Warshall uses dynamic programming across intermediate vertices in O(V^3).' },
    { q: 'Which greedy algorithm finds a Minimum Spanning Tree (MST) by sorting edges and avoiding cycles with Union-Find?', ans: 'Kruskal\'s Algorithm', d1: 'Prim\'s Algorithm', d2: 'Dijkstra\'s Algorithm', d3: 'A* Search', exp: 'Kruskal\'s sorts edges by weight and uses DSU to prevent cycle formation.' },
    { q: 'Which algorithm finds the Minimum Spanning Tree (MST) by growing a tree from an arbitrary starting vertex?', ans: 'Prim\'s Algorithm', d1: 'Kruskal\'s Algorithm', d2: 'Bellman-Ford Algorithm', d3: 'DFS', exp: 'Prim\'s expands the MST by greedily adding the cheapest adjacent cut edge.' },
    { q: 'What is the time complexity of Binary Search on a sorted array of N elements?', ans: 'O(log N)', d1: 'O(N)', d2: 'O(1)', d3: 'O(N log N)', exp: 'Binary search halves the search space in each iteration: O(log2 N).' },
    { q: 'Which sorting algorithm is non-comparison based and operates in O(N + K) time using key counting?', ans: 'Counting Sort', d1: 'QuickSort', d2: 'HeapSort', d3: 'Insertion Sort', exp: 'Counting sort tallies key occurrences in an auxiliary array of range K.' },
    { q: 'What is the worst-case time complexity of Bubble Sort on an array of size N?', ans: 'O(N^2)', d1: 'O(N log N)', d2: 'O(N)', d3: 'O(1)', exp: 'Nested comparisons across N elements produce (N*(N-1))/2 operations = O(N^2).' },
    { q: 'Which algorithmic paradigm solves problems by breaking them into overlapping subproblems and storing results?', ans: 'Dynamic Programming', d1: 'Divide and Conquer', d2: 'Greedy Strategy', d3: 'Backtracking', exp: 'Dynamic Programming combines optimal substructure with memoization of overlapping subproblems.' },
    { q: 'What is the time complexity to find the N-th Fibonacci number using naive recursion?', ans: 'O(2^N)', d1: 'O(N)', d2: 'O(N log N)', d3: 'O(1)', exp: 'Naive recursive Fibonacci creates a branching tree of depth N, taking exponential O(2^N) time.' },
    { q: 'What is the time complexity to find the N-th Fibonacci number using Dynamic Programming memoization?', ans: 'O(N)', d1: 'O(2^N)', d2: 'O(N^2)', d3: 'O(log N)', exp: 'DP computes each of the N subproblems exactly once in O(1) time = O(N).' },
    { q: 'Which string matching algorithm precomputes a Partial Match Table (pi table) to avoid redundant character comparisons?', ans: 'KMP (Knuth-Morris-Pratt) Algorithm', d1: 'Rabin-Karp Algorithm', d2: 'Boyer-Moore Algorithm', d3: 'Naive Matching', exp: 'KMP skips matched prefix alignments using the prefix function pi.' },
    { q: 'Which string search algorithm uses rolling hash values to find matches in O(N + M) average time?', ans: 'Rabin-Karp Algorithm', d1: 'KMP Algorithm', d2: 'Z-Algorithm', d3: 'Manacher\'s Algorithm', exp: 'Rabin-Karp computes rolling polynomial hashes to compare pattern fingerprints.' },
    { q: 'What algorithm produces a linear ordering of vertices in a Directed Acyclic Graph (DAG)?', ans: 'Topological Sort', d1: 'Breadth-First Search', d2: 'Kruskal\'s Algorithm', d3: 'Binary Search', exp: 'Topological sorting orders vertices such that for every directed edge u -> v, u comes before v.' },
    { q: 'Which algorithm finds strongly connected components (SCCs) in a directed graph using two DFS passes?', ans: 'Kosaraju\'s Algorithm', d1: 'Tarjan\'s Algorithm', d2: 'Dijkstra\'s Algorithm', d3: 'Prim\'s Algorithm', exp: 'Kosaraju performs one DFS on the original graph and a second DFS on the transposed graph.' },
    { q: 'What is the auxiliary space complexity of standard in-place HeapSort?', ans: 'O(1)', d1: 'O(N)', d2: 'O(log N)', d3: 'O(N log N)', exp: 'HeapSort arranges elements within the input array without extra allocations, achieving O(1) space.' },
    { q: 'What is the asymptotic lower bound for any comparison-based sorting algorithm in the worst case?', ans: 'Omega(N log N)', d1: 'Omega(N)', d2: 'Omega(log N)', d3: 'Omega(1)', exp: 'A decision tree for sorting N elements has N! leaves, requiring height log2(N!) = Omega(N log N).' },
    { q: 'Which algorithm design technique is used in the N-Queens problem and Sudoku solving?', ans: 'Backtracking', d1: 'Greedy Method', d2: 'Divide and Conquer', d3: 'Linear Programming', exp: 'Backtracking systematically builds candidates and abandons paths as soon as validity is violated.' },
    { q: 'What is the time complexity of the 0/1 Knapsack problem with N items and capacity W using Dynamic Programming?', ans: 'O(N * W)', d1: 'O(2^N)', d2: 'O(N + W)', d3: 'O(N log W)', exp: 'The DP table has dimensions (N+1) x (W+1), filled in pseudo-polynomial O(N*W) time.' },
    { q: 'Which algorithm finds the Longest Palindromic Substring in linear O(N) time?', ans: 'Manacher\'s Algorithm', d1: 'KMP Algorithm', d2: 'Rabin-Karp Algorithm', d3: 'Kadane\'s Algorithm', exp: 'Manacher\'s exploits palindrome symmetry around centers to run in strict O(N) time.' },
    { q: 'Which algorithm finds the maximum subarray sum in a 1D array in linear O(N) time?', ans: 'Kadane\'s Algorithm', d1: 'Dijkstra\'s Algorithm', d2: 'Floyd\'s Algorithm', d3: 'QuickSelect', exp: 'Kadane\'s algorithm tracks the maximum ending at the current position in a single pass.' },
    { q: 'What is the average time complexity of QuickSelect to find the K-th smallest element in an unordered array?', ans: 'O(N)', d1: 'O(N log N)', d2: 'O(log N)', d3: 'O(N^2)', exp: 'By recursing only into the partition containing K, QuickSelect runs in O(N + N/2 + N/4...) = O(N).' },
    { q: 'Which algorithm detects a cycle in a linked list using two pointers moving at different speeds?', ans: 'Floyd\'s Tortoise and Hare Cycle-Finding Algorithm', d1: 'Brent\'s Algorithm', d2: 'Tarjan\'s Algorithm', d3: 'Kruskal\'s Algorithm', exp: 'Slow pointer moves 1 step and fast moves 2 steps; they meet if a cycle exists.' },
    { q: 'What problem class includes problems that can be verified in polynomial time by a deterministic Turing machine?', ans: 'NP (Nondeterministic Polynomial time)', d1: 'P', d2: 'NP-Hard', d3: 'EXPTIME', exp: 'Class NP comprises decision problems whose positive solutions are certifiable in polynomial time.' },
    { q: 'Which heuristic search algorithm extends Dijkstra by utilizing an admissible heuristic h(n) towards the target goal?', ans: 'A* Search Algorithm', d1: 'Breadth-First Search', d2: 'Depth-First Search', d3: 'Bellman-Ford', exp: 'A* evaluates nodes using f(n) = g(n) + h(n), directing search towards the goal.' },
    { q: 'What is the time complexity of building a Binary Heap from an unordered array of N elements (heapify)?', ans: 'O(N)', d1: 'O(N log N)', d2: 'O(log N)', d3: 'O(N^2)', exp: 'Bottom-up heap construction sums geometric terms bounded by 2N = O(N).' },
    { q: 'Which algorithm finds the maximum flow in a flow network by augmenting paths found via BFS?', ans: 'Edmonds-Karp Algorithm', d1: 'Ford-Fulkerson Algorithm', d2: 'Dinic\'s Algorithm', d3: 'Push-Relabel Algorithm', exp: 'Edmonds-Karp implements Ford-Fulkerson using BFS for shortest augmenting paths in O(V * E^2).' },
  ];
  algoData.forEach((a) => {
    addQ(2, 'Algorithms', 'Hard', a.q, a.ans, a.d1, a.d2, a.d3, a.exp);
  });

  // Level 3: Operating Systems (30 distinct questions)
  const osData = [
    { q: 'Which condition is NOT one of Coffman\'s four conditions required for a Deadlock to occur?', ans: 'Preemptive Resource Reallocation', d1: 'Mutual Exclusion', d2: 'Hold and Wait', d3: 'Circular Wait', exp: 'Preemption breaks deadlocks; Coffman conditions include No Preemption, Mutual Exclusion, Hold & Wait, Circular Wait.' },
    { q: 'What is the purpose of the Translation Lookaside Buffer (TLB) in virtual memory systems?', ans: 'To cache recent virtual-to-physical page address translations for faster memory access', d1: 'To store encrypted disk passwords', d2: 'To schedule CPU processes', d3: 'To compress RAM contents' },
    { q: 'Which CPU scheduling algorithm is non-preemptive and selects the process with the smallest execution burst time?', ans: 'Shortest Job First (SJF)', d1: 'Round Robin (RR)', d2: 'First-Come First-Served (FCFS)', d3: 'Priority Scheduling' },
    { q: 'What phenomenon occurs in virtual memory when excessive page faults cause the OS to spend more time swapping pages than executing code?', ans: 'Thrashing', d1: 'Starvation', d2: 'Deadlock', d3: 'Fragmentation' },
    { q: 'What mechanism allows user applications to request privileged services directly from the OS kernel?', ans: 'System Call (e.g., read, write, fork)', d1: 'Hardware Interrupt', d2: 'Context Switch', d3: 'Page Fault' },
    { q: 'In UNIX, which system call creates a new child process by duplicating the calling parent process?', ans: 'fork()', d1: 'exec()', d2: 'wait()', d3: 'pthread_create()' },
    { q: 'Which synchronization primitive provides integer-based counting to control access to a shared resource by multiple threads?', ans: 'Counting Semaphore', d1: 'Mutex Lock', d2: 'Spinlock', d3: 'Atomic Boolean' },
    { q: 'What is the critical section in concurrent programming?', ans: 'A segment of code accessing shared resources that must not be concurrently executed by multiple threads', d1: 'The boot sector of a hard drive', d2: 'The kernel initialization routine', d3: 'The CPU cache hierarchy' },
    { q: 'Which page replacement algorithm replaces the page that will not be used for the longest period of time in the future?', ans: 'Optimal Page Replacement (OPT / Belady\'s)', d1: 'Least Recently Used (LRU)', d2: 'First In First Out (FIFO)', d3: 'Least Frequently Used (LFU)' },
    { q: 'What is Belady\'s Anomaly in operating systems memory management?', ans: 'A phenomenon where increasing the number of page frames results in an increased number of page faults (under FIFO)', d1: 'A CPU deadlock in multicore systems', d2: 'Memory leaks in user space', d3: 'Disk fragmentation on SSDs' },
    { q: 'What happens during a CPU Context Switch?', ans: 'The state (registers, PC) of the active process is saved and the state of another scheduled process is restored', d1: 'The power supply voltage switches', d2: 'The hard drive is reformatted', d3: 'The BIOS flashes new firmware' },
    { q: 'Which memory allocation issue occurs when free memory is broken into small non-contiguous blocks scattered throughout RAM?', ans: 'External Fragmentation', d1: 'Internal Fragmentation', d2: 'Page Thrashing', d3: 'Segment Fault' },
    { q: 'What is Internal Fragmentation in paging systems?', ans: 'Unused allocated memory space inside a fixed-size page block', d1: 'Unallocated memory between blocks', d2: 'Disk sector failure', d3: 'Register spillover' },
    { q: 'Which scheduling algorithm assigns each ready process a fixed time quantum in cyclic order?', ans: 'Round Robin (RR)', d1: 'Shortest Remaining Time First', d2: 'Priority Scheduling', d3: 'FCFS' },
    { q: 'What is a Daemon process in UNIX/Linux systems?', ans: 'A background service process that runs without direct user interaction', d1: 'A virus infecting the kernel', d2: 'A corrupted file on disk', d3: 'A stopped terminal application' },
    { q: 'What is an Inode in UNIX-like file systems?', ans: 'A data structure that stores metadata about a file (permissions, size, block locations) except its name', d1: 'A network socket buffer', d2: 'A CPU cache line', d3: 'A RAM paging frame' },
    { q: 'Which deadlock avoidance algorithm tests for safe resource allocation states before granting requests?', ans: 'Banker\'s Algorithm', d1: 'Dijkstra\'s Algorithm', d2: 'Peterson\'s Algorithm', d3: 'Lamport\'s Bakery Algorithm' },
    { q: 'What is the main difference between a Process and a Thread?', ans: 'Processes have independent virtual address spaces, while threads within a process share the same address space and memory', d1: 'Processes run on GPU, threads run on CPU', d2: 'Threads have isolated files, processes do not', d3: 'Processes cannot be scheduled' },
    { q: 'What is a Zombie Process in UNIX?', ans: 'A process that has finished execution but still has an entry in the process table because its parent has not read its exit status', d1: 'A process stuck in an infinite loop', d2: 'A process killed by the kernel', d3: 'A process without any memory allocation' },
    { q: 'What is an Orphan Process in UNIX?', ans: 'A running process whose parent process terminated before it, subsequently adopted by init / systemd (PID 1)', d1: 'A process that failed to compile', d2: 'A thread detached from its process', d3: 'A process with a closed standard output' },
    { q: 'Which inter-process communication (IPC) mechanism provides unidirectional data flow between related processes using file descriptors?', ans: 'Pipe (Anonymous Pipe)', d1: 'Shared Memory', d2: 'Message Queue', d3: 'Signal' },
    { q: 'What is Direct Memory Access (DMA)?', ans: 'Hardware feature allowing I/O devices to transfer data directly to/from RAM without continuous CPU intervention', d1: 'Direct access to CPU registers', d2: 'Bypassing the operating system kernel', d3: 'Unencrypted RAM reading' },
    { q: 'Which RAID level uses disk striping with distributed parity across at least 3 drives?', ans: 'RAID 5', d1: 'RAID 0', d2: 'RAID 1', d3: 'RAID 10' },
    { q: 'What is the primary role of the CPU Interrupt Service Routine (ISR)?', ans: 'To handle asynchronous hardware or software interrupt signals and resume prior execution', d1: 'To reboot the computer', d2: 'To schedule disk defragmentation', d3: 'To allocate RAM pages' },
    { q: 'Which algorithm solves the 2-process critical section problem with mutual exclusion, progress, and bounded waiting in software?', ans: 'Peterson\'s Algorithm', d1: 'Banker\'s Algorithm', d2: 'Round Robin', d3: 'LRU Algorithm' },
    { q: 'What does the POSIX standard define in operating systems?', ans: 'A standardized API interface between operating systems and software applications for cross-platform portability', d1: 'A hardware bus pinout specification', d2: 'An encryption key format', d3: 'A monitor refresh rate standard' },
    { q: 'What is the Swap Space on a hard drive or SSD used for?', ans: 'To temporarily hold inactive memory pages evicted from physical RAM', d1: 'To store BIOS settings', d2: 'To archive old application logs', d3: 'To cache CPU instructions' },
    { q: 'What is Starvation in OS process scheduling?', ans: 'A situation where a low-priority process is indefinitely delayed because high-priority processes monopolize the CPU', d1: 'The computer running out of battery power', d2: 'A hard disk having zero remaining space', d3: 'A network cable disconnection' },
    { q: 'How does Aging prevent starvation in priority scheduling?', ans: 'By gradually increasing the priority of processes that wait in the ready queue for a long time', d1: 'By terminating old processes', d2: 'By lowering CPU clock speeds', d3: 'By rebooting the server daily' },
    { q: 'What is copy-on-write (COW) optimization used during process creation (fork)?', ans: 'Parent and child share identical memory pages until either process writes to a page, triggering a duplicate page copy', d1: 'Copying all memory instantly during fork', d2: 'Writing all logs to physical disk immediately', d3: 'Duplicating files when opened' },
  ];
  osData.forEach((o) => {
    addQ(3, 'Operating Systems', 'Medium', o.q, o.ans, o.d1, o.d2, o.d3, o.exp);
  });

  // Level 4: Database Management Systems (DBMS) (30 distinct questions)
  const dbData = [
    { q: 'In relational database schema design, which Normal Form eliminates transitive functional dependencies?', ans: 'Third Normal Form (3NF)', d1: 'First Normal Form (1NF)', d2: 'Second Normal Form (2NF)', d3: 'Boyce-Codd Normal Form (BCNF)' },
    { q: 'Which Normal Form requires every non-prime attribute to be fully functionally dependent on the entire primary key (no partial dependencies)?', ans: 'Second Normal Form (2NF)', d1: 'First Normal Form (1NF)', d2: 'Third Normal Form (3NF)', d3: 'Fourth Normal Form (4NF)' },
    { q: 'What does the \'A\' in database ACID transaction properties stand for?', ans: 'Atomicity (All operations in the transaction succeed, or all are rolled back)', d1: 'Availability', d2: 'Asynchronous', d3: 'Authentication' },
    { q: 'What does the \'I\' in ACID transaction guarantees ensure?', ans: 'Isolation (Concurrent transactions execute without interfering with one another)', d1: 'Integrity', d2: 'Indexing', d3: 'Idempotency' },
    { q: 'Which SQL clause is used to filter groups of records created by a GROUP BY clause?', ans: 'HAVING', d1: 'WHERE', d2: 'ORDER BY', d3: 'LIMIT' },
    { q: 'What type of database JOIN returns all records from the left table and matched records from the right table?', ans: 'LEFT OUTER JOIN', d1: 'INNER JOIN', d2: 'RIGHT OUTER JOIN', d3: 'CROSS JOIN' },
    { q: 'Which data structure is most commonly used for database table indexing because of high fan-out and sequential range scans?', ans: 'B+ Tree', d1: 'Binary Search Tree', d2: 'Skip List', d3: 'Linked List' },
    { q: 'What is a Primary Key in a relational database table?', ans: 'A column or set of columns that uniquely identifies each row and cannot contain NULL values', d1: 'A key that encrypts data', d2: 'A foreign table reference', d3: 'An optional non-unique index' },
    { q: 'What is a Foreign Key constraint?', ans: 'A field in one table that uniquely identifies a row of another table, enforcing referential integrity', d1: 'A key generated by external APIs', d2: 'A secondary encryption password', d3: 'An auto-incrementing integer' },
    { q: 'In SQL concurrency, what is a Dirty Read?', ans: 'A transaction reads uncommitted data modifications made by another concurrent transaction that might later roll back', d1: 'Reading data from a corrupted hard disk', d2: 'Reading data without using an index', d3: 'Executing a query with syntax errors' },
    { q: 'Which SQL Transaction Isolation level prevents Dirty Reads, Non-repeatable Reads, and Phantom Reads completely?', ans: 'Serializable', d1: 'Read Committed', d2: 'Read Uncommitted', d3: 'Repeatable Read' },
    { q: 'What is Write-Ahead Logging (WAL) in database storage engines?', ans: 'Changes are written to a persistent append-only log on disk before modifying in-memory data pages', d1: 'Writing logs after data is deleted', d2: 'Logging all user search terms', d3: 'Writing code documentation in advance' },
    { q: 'What is a View in SQL databases?', ans: 'A virtual table based on the result set of a predefined SQL query', d1: 'A physical copy of table data on disk', d2: 'A database backup snapshot', d3: 'A UI interface widget' },
    { q: 'Which SQL command permanently saves all changes made during the current transaction to the database?', ans: 'COMMIT', d1: 'ROLLBACK', d2: 'SAVEPOINT', d3: 'GRANT' },
    { q: 'Which SQL command undos all changes made during the current uncommitted transaction?', ans: 'ROLLBACK', d1: 'COMMIT', d2: 'REVOKE', d3: 'TRUNCATE' },
    { q: 'What is the key difference between DROP TABLE and TRUNCATE TABLE in SQL?', ans: 'DROP removes the table schema and data entirely, while TRUNCATE deletes all rows but preserves table structure', d1: 'DROP is faster than TRUNCATE', d2: 'TRUNCATE deletes the database', d3: 'DROP can be rolled back without logs' },
    { q: 'What is a Clustered Index in relational databases?', ans: 'An index that determines the physical order of data rows on disk (only one clustered index per table)', d1: 'An index distributed across multiple servers', d2: 'An index that stores duplicate keys', d3: 'An index on temporary tables only' },
    { q: 'What is Database Sharding?', ans: 'A horizontal partitioning technique that splits a large database across multiple independent physical servers', d1: 'Encrypting database columns', d2: 'Creating database backups on tape', d3: 'Creating table views' },
    { q: 'What does NoSQL stand for in modern data management?', ans: 'Not Only SQL (Non-relational, flexible-schema database systems)', d1: 'No Software Queries Allowed', d2: 'New Online SQL', d3: 'Node-Only SQL' },
    { q: 'Which type of NoSQL database is MongoDB categorized as?', ans: 'Document Store (JSON/BSON)', d1: 'Key-Value Store', d2: 'Wide-Column Store', d3: 'Graph Database' },
    { q: 'Which type of NoSQL database is Neo4j categorized as?', ans: 'Graph Database', d1: 'Document Store', d2: 'Key-Value Store', d3: 'Relational Database' },
    { q: 'Which type of NoSQL database is Redis primarily categorized as?', ans: 'In-Memory Key-Value Store', d1: 'Relational Table Store', d2: 'Graph Database', d3: 'XML Document Store' },
    { q: 'In relational algebra, which operator filters rows that satisfy a given predicate condition?', ans: 'Selection (sigma)', d1: 'Projection (pi)', d2: 'Cartesian Product (X)', d3: 'Union (U)' },
    { q: 'In relational algebra, which operator selects specific columns from a relation table?', ans: 'Projection (pi)', d1: 'Selection (sigma)', d2: 'Intersection', d3: 'Difference' },
    { q: 'What is a Stored Procedure in SQL?', ans: 'A precompiled set of SQL statements and procedural logic stored and executed on the database server', d1: 'A user manual for the database', d2: 'A database installation script', d3: 'A client-side JavaScript function' },
    { q: 'What is a Database Trigger?', ans: 'A procedural block of code that automatically executes in response to specified table events (INSERT, UPDATE, DELETE)', d1: 'A button in database management software', d2: 'A scheduled cron backup job', d3: 'A hardware error alarm' },
    { q: 'What is Two-Phase Locking (2PL) protocol used for in DBMS concurrency control?', ans: 'To guarantee transaction serializability through a growing phase (acquiring locks) and shrinking phase (releasing locks)', d1: 'To encrypt passwords in two steps', d2: 'To create two backup copies', d3: 'To connect via two network cards' },
    { q: 'What is a Candidate Key in relational schema design?', ans: 'A minimal set of attributes that uniquely identifies a tuple in a relation, eligible to become the primary key', d1: 'A key that failed validation', d2: 'A foreign key candidate', d3: 'A non-unique index' },
    { q: 'What is Database Denormalization?', ans: 'Strategically adding redundancy to normalized tables to optimize read performance and avoid expensive multi-table joins', d1: 'Deleting primary keys', d2: 'Corrupting database indexes', d3: 'Converting SQL to plain text' },
    { q: 'What is the purpose of an EXPLAIN query in SQL database engines?', ans: 'To display the query execution plan, showing index usage, join types, and cost estimates chosen by the optimizer', d1: 'To explain SQL syntax to beginners', d2: 'To execute the query 100 times', d3: 'To format output with color' },
  ];
  dbData.forEach((d) => {
    addQ(4, 'DBMS', 'Medium', d.q, d.ans, d.d1, d.d2, d.d3, (d as any).exp || `Correct resolution: ${d.ans}.`);
  });

  // Level 5: Computer Networks (30 distinct questions)
  const netData = [
    { q: 'Which OSI model layer handles logical IP addressing and packet routing across networks?', ans: 'Network Layer (Layer 3)', d1: 'Data Link Layer (Layer 2)', d2: 'Transport Layer (Layer 4)', d3: 'Session Layer (Layer 5)' },
    { q: 'Which OSI layer is responsible for node-to-node framing, physical MAC addressing, and error detection?', ans: 'Data Link Layer (Layer 2)', d1: 'Physical Layer (Layer 1)', d2: 'Network Layer (Layer 3)', d3: 'Application Layer (Layer 7)' },
    { q: 'What is the primary difference between TCP and UDP transport protocols?', ans: 'TCP is connection-oriented and reliable with acknowledgments; UDP is connectionless and low-overhead without guarantees', d1: 'TCP is wireless, UDP is wired', d2: 'UDP encrypts data, TCP does not', d3: 'TCP operates at Layer 7, UDP at Layer 2' },
    { q: 'What is the standard port number used for secure HTTPS web traffic?', ans: 'Port 443', d1: 'Port 80', d2: 'Port 22', d3: 'Port 8080' },
    { q: 'What is the standard port number for SSH (Secure Shell) remote terminal access?', ans: 'Port 22', d1: 'Port 21', d2: 'Port 23', d3: 'Port 25' },
    { q: 'What is the role of the DNS (Domain Name System) protocol?', ans: 'To translate human-readable domain names (e.g. example.com) into numerical IP addresses (e.g. 93.184.216.34)', d1: 'To assign dynamic IP addresses to devices', d2: 'To encrypt email messages', d3: 'To route audio packets' },
    { q: 'What protocol dynamically assigns IP addresses, subnet masks, and default gateways to client devices on a local network?', ans: 'DHCP (Dynamic Host Configuration Protocol)', d1: 'DNS', d2: 'ARP', d3: 'ICMP' },
    { q: 'Which protocol maps a known 32-bit IPv4 address to a physical 48-bit MAC hardware address?', ans: 'ARP (Address Resolution Protocol)', d1: 'RARP', d2: 'DHCP', d3: 'NAT' },
    { q: 'What is the bit length of a standard IPv6 address?', ans: '128 bits', d1: '32 bits', d2: '64 bits', d3: '256 bits' },
    { q: 'What is the bit length of a standard IPv4 address?', ans: '32 bits', d1: '16 bits', d2: '64 bits', d3: '128 bits' },
    { q: 'What steps constitute the standard TCP Three-Way Handshake connection establishment?', ans: 'SYN -> SYN-ACK -> ACK', d1: 'ACK -> SYN -> ACK', d2: 'HELLO -> ACK -> DATA', d3: 'CONNECT -> ACCEPT -> READY' },
    { q: 'What is Network Address Translation (NAT) used for in routers?', ans: 'To map multiple private local IP addresses to a single public IP address for internet access', d1: 'To convert IPv4 into IPv6 automatically', d2: 'To scan packets for computer viruses', d3: 'To boost WiFi transmission range' },
    { q: 'Which protocol is used by network utilities like `ping` and `traceroute` for diagnostics and error reporting?', ans: 'ICMP (Internet Control Message Protocol)', d1: 'IGMP', d2: 'SNMP', d3: 'SMTP' },
    { q: 'What is the Maximum Transmission Unit (MTU) typically set to on standard Ethernet networks?', ans: '1500 bytes', d1: '512 bytes', d2: '4096 bytes', d3: '65535 bytes' },
    { q: 'What routing algorithm is used by BGP (Border Gateway Protocol) to route traffic between Autonomous Systems on the global Internet?', ans: 'Path-Vector Routing', d1: 'Distance-Vector Routing', d2: 'Link-State Routing', d3: 'Flooding' },
    { q: 'Which link-state routing protocol uses Dijkstra\'s algorithm within an Autonomous System?', ans: 'OSPF (Open Shortest Path First)', d1: 'RIP', d2: 'BGP', d3: 'EGP' },
    { q: 'What is the purpose of the TTL (Time to Live) field in an IPv4 packet header?', ans: 'To prevent packets from circulating endlessly in routing loops by decrementing at each hop until reaching 0', d1: 'To measure packet download speed', d2: 'To track timestamp of packet creation', d3: 'To set cache expiration' },
    { q: 'What mechanism does TCP use to prevent a fast sender from overwhelming a slow receiver\'s buffer?', ans: 'Flow Control (Sliding Window)', d1: 'Congestion Control', d2: 'Checksumming', d3: 'Encryption' },
    { q: 'What TCP mechanism detects and reacts to network bottlenecks by adjusting the `cwnd` (congestion window)?', ans: 'Congestion Control (e.g. Slow Start, AIMD, Reno/Cubic)', d1: 'Flow Control', d2: 'DNS Resolution', d3: 'Subnetting' },
    { q: 'What is a Subnet Mask used for in IP networking?', ans: 'To distinguish the network portion from the host portion of an IP address', d1: 'To hide the IP address from websites', d2: 'To encrypt network packets', d3: 'To increase network bandwidth' },
    { q: 'What is CIDR notation for the subnet mask 255.255.255.0?', ans: '/24', d1: '/16', d2: '/8', d3: '/32' },
    { q: 'Which protocol provides secure cryptographic communication over computer networks using symmetric encryption and asymmetric key exchange?', ans: 'TLS (Transport Layer Security)', d1: 'HTTP', d2: 'FTP', d3: 'Telnet' },
    { q: 'What is the primary function of a Network Switch operating at Layer 2?', ans: 'To forward Ethernet frames to specific destination ports using a MAC address table', d1: 'To route packets across different IP subnets', d2: 'To convert digital signals into analog', d3: 'To assign domain names' },
    { q: 'What is a Collision Domain in computer networking?', ans: 'A network segment where simultaneous packet transmissions collide with each other (e.g. half-duplex hubs)', d1: 'A group of computers sharing a subnet', d2: 'A server rack in a data center', d3: 'A range of blocked IP addresses' },
    { q: 'What is a Broadcast Domain?', ans: 'A logical division of a computer network in which all nodes can reach each other by broadcast at the data link layer', d1: 'A television channel frequency', d2: 'A single Ethernet cable wire', d3: 'A firewall rule set' },
    { q: 'Which protocol is used for sending outgoing emails across mail servers on the Internet?', ans: 'SMTP (Simple Mail Transfer Protocol)', d1: 'IMAP', d2: 'POP3', d3: 'HTTP' },
    { q: 'Which email protocol downloads emails from the mail server to a local client and typically removes them from the server?', ans: 'POP3 (Post Office Protocol 3)', d1: 'IMAP', d2: 'SMTP', d3: 'SNMP' },
    { q: 'Which email protocol synchronizes messages bidirectionally across multiple devices while keeping mail stored on the server?', ans: 'IMAP (Internet Message Access Protocol)', d1: 'POP3', d2: 'SMTP', d3: 'FTP' },
    { q: 'What is the loopback IPv4 address reserved for testing network software on the local host machine?', ans: '127.0.0.1 (localhost)', d1: '192.168.1.1', d2: '10.0.0.1', d3: '255.255.255.255' },
    { q: 'What is the default subnet prefix assigned to private Class C networks (e.g. 192.168.0.0/16)?', ans: '192.168.0.0 to 192.168.255.255 (RFC 1918)', d1: '10.0.0.0 to 10.255.255.255', d2: '172.16.0.0 to 172.31.255.255', d3: '127.0.0.0 to 127.255.255.255' },
  ];
  netData.forEach((n) => {
    addQ(5, 'Computer Networks', 'Medium', n.q, n.ans, n.d1, n.d2, n.d3, (n as any).exp || `Correct resolution: ${n.ans}.`);
  });

  // Level 6: Object-Oriented Programming (OOP) (30 distinct questions)
  const oopData = [
    { q: 'Which OOP pillar bundles data fields and methods that manipulate that data into a single unit while restricting direct access?', ans: 'Encapsulation', d1: 'Inheritance', d2: 'Polymorphism', d3: 'Abstraction' },
    { q: 'Which OOP concept allows derived subclasses to provide specific implementations of methods defined in base parent classes?', ans: 'Dynamic Polymorphism (Method Overriding)', d1: 'Encapsulation', d2: 'Static Binding', d3: 'Tight Coupling' },
    { q: 'What is Method Overloading (Compile-Time Polymorphism)?', ans: 'Defining multiple methods in the same class with identical names but different parameter signatures', d1: 'Overriding a method in a child class', d2: 'Hiding private class attributes', d3: 'Calling a parent constructor' },
    { q: 'What is an Abstract Class in object-oriented design?', ans: 'A class that cannot be instantiated directly and is intended to serve as a blueprint with abstract methods for subclasses', d1: 'A class that has no methods', d2: 'A class without constructor', d3: 'A class that can only be instantiated once' },
    { q: 'What is an Interface in programming languages like Java or TypeScript?', ans: 'A contract defining method signatures and property shapes without providing concrete implementation code', d1: 'A GUI screen layout', d2: 'A private variable scope', d3: 'A runtime database connection' },
    { q: 'What does the \'S\' in SOLID object-oriented design principles stand for?', ans: 'Single Responsibility Principle (A class should have only one reason to change)', d1: 'Static Typing Principle', d2: 'Subclass Isolation Principle', d3: 'Sequential Execution Principle' },
    { q: 'What does the \'O\' in SOLID principles state?', ans: 'Open/Closed Principle (Software entities should be open for extension, but closed for modification)', d1: 'Object Oriented Principle', d2: 'Operator Overloading Principle', d3: 'Optimal Memory Principle' },
    { q: 'What does the \'L\' in SOLID principles stand for?', ans: 'Liskov Substitution Principle (Subtypes must be substitutable for their base types without altering program correctness)', d1: 'Lazy Loading Principle', d2: 'Linear Inheritance Principle', d3: 'Loose Coupling Principle' },
    { q: 'What does the \'I\' in SOLID principles demand?', ans: 'Interface Segregation Principle (Clients should not be forced to depend on methods they do not use)', d1: 'Immutable State Principle', d2: 'Inheritance Hierarchy Principle', d3: 'Instance Binding Principle' },
    { q: 'What does the \'D\' in SOLID design principles state?', ans: 'Dependency Inversion Principle (High-level modules should depend on abstractions, not on concrete low-level details)', d1: 'Data Encapsulation Principle', d2: 'Destructor Execution Principle', d3: 'Dynamic Dispatch Principle' },
    { q: 'Which creational design pattern ensures a class has only one instance and provides a global access point to it?', ans: 'Singleton Pattern', d1: 'Factory Pattern', d2: 'Prototype Pattern', d3: 'Builder Pattern' },
    { q: 'Which structural design pattern allows incompatible interfaces to work together by wrapping an existing object?', ans: 'Adapter Pattern', d1: 'Observer Pattern', d2: 'Strategy Pattern', d3: 'Decorator Pattern' },
    { q: 'Which behavioral design pattern defines a one-to-many subscription dependency between objects so that state changes trigger updates?', ans: 'Observer Pattern', d1: 'Singleton Pattern', d2: 'Factory Method', d3: 'Flyweight Pattern' },
    { q: 'Which design pattern defines a family of algorithms, encapsulates each one, and makes them interchangeable at runtime?', ans: 'Strategy Pattern', d1: 'Command Pattern', d2: 'Decorator Pattern', d3: 'Facade Pattern' },
    { q: 'Which structural design pattern dynamically attaches additional responsibilities and behaviors to an object without subclassing?', ans: 'Decorator Pattern', d1: 'Adapter Pattern', d2: 'Composite Pattern', d3: 'Proxy Pattern' },
    { q: 'What is the Diamond Problem in multiple inheritance, and how is it resolved?', ans: 'Ambiguity when a class inherits from two parent classes that both derive from a common ancestor; resolved via virtual base classes or interfaces', d1: 'A CPU memory alignment crash', d2: 'A hard disk storage defect', d3: 'A circular dependency in packages' },
    { q: 'What is Composition over Inheritance principle in software engineering?', ans: 'Preferring to combine simple objects with specific capabilities rather than building rigid multi-level inheritance hierarchies', d1: 'Always using abstract classes', d2: 'Avoiding all functions', d3: 'Using global variables' },
    { q: 'What is the role of a Constructor in object-oriented programming?', ans: 'A special method called automatically upon object creation to initialize object state and allocate resources', d1: 'To delete unused objects', d2: 'To compile bytecode', d3: 'To render HTML components' },
    { q: 'What is a Destructor (or finalizer)?', ans: 'A method invoked automatically when an object is destroyed or garbage collected to release unmanaged resources', d1: 'A compiler error handler', d2: 'A constructor with arguments', d3: 'An abstract interface' },
    { q: 'What does the `this` (or `self`) keyword reference in object methods?', ans: 'The current instance of the class executing the method', d1: 'The parent superclass', d2: 'The global window object', d3: 'The operating system kernel' },
    { q: 'What is the difference between shallow copy and deep copy of an object?', ans: 'Shallow copy duplicates top-level primitives and copies nested object references; deep copy recursively duplicates all nested objects', d1: 'Shallow copy is on disk, deep copy is in RAM', d2: 'Deep copy encrypts data', d3: 'Shallow copy modifies original values' },
    { q: 'What is Polymorphism through Duck Typing in dynamically typed languages like Python or JavaScript?', ans: '"If it walks like a duck and quacks like a duck, it\'s a duck" - matching objects based on method existence rather than explicit class type', d1: 'Strict compiler inheritance checking', d2: 'Converting strings to integers', d3: 'Using animal naming conventions' },
    { q: 'Which design pattern provides a unified, simplified high-level interface to a complex subsystem of classes?', ans: 'Facade Pattern', d1: 'Bridge Pattern', d2: 'Flyweight Pattern', d3: 'Proxy Pattern' },
    { q: 'Which design pattern separates the construction of a complex object from its representation, allowing step-by-step assembly?', ans: 'Builder Pattern', d1: 'Factory Pattern', d2: 'Singleton Pattern', d3: 'Visitor Pattern' },
    { q: 'What is Coupling in software architecture, and what is the recommended design goal?', ans: 'The degree of direct interdependence between software modules; low (loose) coupling is the recommended goal', d1: 'High coupling is always preferred', d2: 'Coupling measures memory usage', d3: 'Coupling refers to network latency' },
    { q: 'What is Cohesion in module design, and what is the recommended practice?', ans: 'The degree to which elements within a module belong together and serve a unified single purpose; high cohesion is recommended', d1: 'Low cohesion is preferred', d2: 'Cohesion measures file size', d3: 'Cohesion counts lines of code' },
    { q: 'What is Reflection in programming languages?', ans: 'The ability of a running program to examine, introspect, and modify its own class structures, methods, and metadata at runtime', d1: 'Mirroring database tables', d2: 'Light scattering in optical fibers', d3: 'Displaying UI on dual monitors' },
    { q: 'What is an Immutable Object in OOP?', ans: 'An object whose internal state cannot be modified after it is created', d1: 'An object that cannot be copied', d2: 'An object stored only on disk', d3: 'An object without any methods' },
    { q: 'Which design pattern encapsulates a request as an object, thereby letting you parameterize clients with different requests, queue or log requests, and support undo operations?', ans: 'Command Pattern', d1: 'State Pattern', d2: 'Observer Pattern', d3: 'Template Method' },
    { q: 'What is Dependency Injection (DI) in software development?', ans: 'A technique where an object receives its dependencies from an external assembler rather than creating them internally', d1: 'Injecting malicious SQL strings', d2: 'Writing hardcoded connection strings', d3: 'Overriding system memory' },
  ];
  oopData.forEach((o) => {
    addQ(6, 'OOP Concepts', 'Medium', o.q, o.ans, o.d1, o.d2, o.d3, (o as any).exp || `Correct resolution: ${o.ans}.`);
  });

  // Level 7: Web Technologies & APIs (30 distinct questions)
  const webData = [
    { q: 'Which HTTP request method is specified by RFC standards as idempotent and used to replace an entire entity resource?', ans: 'PUT', d1: 'POST', d2: 'PATCH', d3: 'CONNECT' },
    { q: 'Which HTTP method is designed for applying partial modifications to a server resource?', ans: 'PATCH', d1: 'PUT', d2: 'POST', d3: 'GET' },
    { q: 'What does the HTTP 401 Unauthorized status code indicate?', ans: 'The request requires user authentication credentials that are missing or invalid', d1: 'The server cannot find the requested resource', d2: 'The user is authenticated but forbidden from accessing the resource', d3: 'Internal server error occurred' },
    { q: 'What does the HTTP 403 Forbidden status code indicate?', ans: 'The client is authenticated, but does not have permission/authorization to access the requested resource', d1: 'Missing login credentials', d2: 'Page not found', d3: 'Server timeout' },
    { q: 'What is CORS (Cross-Origin Resource Sharing) in web security?', ans: 'A browser security mechanism that uses HTTP headers to determine whether a web page can load resources from another domain', d1: 'An image compression format', d2: 'A database query language', d3: 'A CSS flexbox property' },
    { q: 'What does the HTTP 429 Too Many Requests status code represent?', ans: 'The client has exceeded rate limiting thresholds within a given time window', d1: 'The server is permanently down', d2: 'The request body is corrupted', d3: 'DNS lookup failed' },
    { q: 'What is the purpose of JWT (JSON Web Token) in modern web applications?', ans: 'To securely transmit claims and authentication state between parties as a digitally signed, compact JSON string', d1: 'To compress video streams', d2: 'To replace CSS stylesheets', d3: 'To style HTML buttons' },
    { q: 'Which part of a JWT contains the cryptographic signature verifying token integrity?', ans: 'The third segment (after the second period delimiter)', d1: 'The Header', d2: 'The Payload', d3: 'The Cookie header' },
    { q: 'What does the SameSite cookie attribute with value `Strict` accomplish?', ans: 'Prevents the browser from sending the cookie in cross-site requests, mitigating CSRF (Cross-Site Request Forgery)', d1: 'Encrypts the cookie with RSA', d2: 'Deletes the cookie after 5 seconds', d3: 'Allows any domain to read the cookie' },
    { q: 'What is the purpose of the `HttpOnly` flag on HTTP cookies?', ans: 'Prevents client-side JavaScript (e.g. document.cookie) from accessing the cookie, protecting against XSS token theft', d1: 'Forces the cookie to use HTTP instead of HTTPS', d2: 'Disables all cookies in the browser', d3: 'Limits cookies to mobile devices' },
    { q: 'What is the DOM (Document Object Model) in web browsers?', ans: 'A tree-like in-memory object representation of an HTML document that JavaScript can traverse and manipulate', d1: 'A database server storage engine', d2: 'A CSS color specification', d3: 'A network routing table' },
    { q: 'What is Event Bubbling in browser JavaScript event propagation?', ans: 'An event triggers on the deepest target element first and then propagates upwards through its parent ancestor nodes in the DOM tree', d1: 'Events dropping silently', d2: 'Events moving only downwards from window to target', d3: 'Events executing across different tabs' },
    { q: 'How does `event.stopPropagation()` affect event bubbling in the DOM?', ans: 'It prevents the event from propagating further up the parent hierarchy', d1: 'It prevents the default browser behavior', d2: 'It reloads the web page', d3: 'It deletes the target DOM element' },
    { q: 'What is the purpose of `event.preventDefault()` in JavaScript event handlers?', ans: 'It stops the browser\'s default action for that event (such as submitting a form or following a hyperlink)', d1: 'It stops event bubbling', d2: 'It clears localStorage', d3: 'It logs out the active user' },
    { q: 'What is the Event Loop in JavaScript runtimes (V8 / Node.js / Browsers)?', ans: 'A continuous mechanism that monitors the Call Stack and Task Queue, pushing callback tasks onto the stack when it is empty', d1: 'A `for` loop that never terminates', d2: 'A multi-threaded CPU scheduler', d3: 'A CSS keyframe animation loop' },
    { q: 'What is the execution order difference between Microtasks (e.g. Promises) and Macrotasks (e.g. setTimeout) in JavaScript?', ans: 'All pending Microtasks are executed immediately after the current call stack clears before the next Macrotask is processed', d1: 'Macrotasks always execute before Microtasks', d2: 'Microtasks and Macrotasks run in parallel threads', d3: 'Microtasks only run on page reload' },
    { q: 'What is a Closure in JavaScript and functional programming?', ans: 'A function bundled together with references to its surrounding lexical environment, allowing it to access outer variables even after the outer function has returned', d1: 'A closed browser tab', d2: 'A completed network request', d3: 'A private class method only' },
    { q: 'What is WebAssembly (Wasm)?', ans: 'A binary instruction format for a stack-based virtual machine, enabling high-performance execution of C/C++/Rust code in web browsers near native speed', d1: 'A replacement for HTML markup', d2: 'A new CSS framework', d3: 'An Apache web server module' },
    { q: 'What is a Service Worker in modern web applications?', ans: 'A background script running independently of web pages that can intercept network requests, manage caching, and handle push notifications', d1: 'A customer service chat bot', d2: 'A server database worker', d3: 'A CSS preprocessor' },
    { q: 'What is the purpose of Content Security Policy (CSP) HTTP headers?', ans: 'To restrict the sources from which scripts, styles, images, and other resources can be loaded, preventing Cross-Site Scripting (XSS)', d1: 'To speed up file downloads', d2: 'To translate web pages into foreign languages', d3: 'To configure DNS records' },
    { q: 'What does the HTTP 304 Not Modified status code inform the browser?', ans: 'The cached copy of the resource is still fresh and valid; the server does not retransmit the response body', d1: 'The page was deleted', d2: 'The user has no permission', d3: 'The database rejected the update' },
    { q: 'What is GraphQL schema introspection?', ans: 'The ability of a client to query the GraphQL server for metadata about its types, queries, mutations, and fields', d1: 'Scanning server memory for security keys', d2: 'Analyzing SQL execution plans', d3: 'Viewing browser history' },
    { q: 'What is the purpose of the HTTP `Cache-Control: max-age=3600, immutable` header directive?', ans: 'Instructs browsers and proxies that the response can be cached for 3600 seconds and will never change during that period', d1: 'Deletes the cache immediately', d2: 'Encrypts the file with AES', d3: 'Requires revalidation on every click' },
    { q: 'What is the Critical Rendering Path in browser page loading?', ans: 'The sequence of steps the browser takes (HTML parsing -> DOM -> CSSOM -> Render Tree -> Layout -> Paint) to render pixels on screen', d1: 'The shortest distance across network routers', d2: 'The database query optimization path', d3: 'The server boot sequence' },
    { q: 'What does `localStorage` in browser Web Storage API provide?', ans: 'Persistent key-value client-side storage (~5-10MB) with no expiration date across browser sessions', d1: 'Session-only storage deleted on tab close', d2: 'Encrypted cloud storage', d3: 'Direct server database access' },
    { q: 'What is the difference between `localStorage` and `sessionStorage`?', ans: '`sessionStorage` data is cleared when the specific browser tab is closed; `localStorage` persists indefinitely until cleared', d1: '`sessionStorage` stores images, `localStorage` stores text', d2: '`localStorage` is sent to the server in HTTP headers', d3: '`sessionStorage` requires user password' },
    { q: 'What is Server-Sent Events (SSE)?', ans: 'A standard enabling a web server to push unidirectional, real-time text updates to web clients over a single long-lived HTTP connection', d1: 'Full-duplex binary communication', d2: 'Polling the server every second', d3: 'Sending emails from servers' },
    { q: 'What is the difference between WebSockets and Server-Sent Events (SSE)?', ans: 'WebSockets provide full-duplex bi-directional communication; SSE provides server-to-client unidirectional streaming over HTTP', d1: 'WebSockets only send text, SSE sends binary', d2: 'SSE is deprecated', d3: 'WebSockets do not use TCP' },
    { q: 'What is Tree Shaking in modern JavaScript bundlers (Webpack, Vite, Rollup)?', ans: 'A dead-code elimination optimization that removes unused ES module exports from the final production bundle', d1: 'Restarting the server automatically', d2: 'Testing DOM nodes for errors', d3: 'Minifying CSS class names' },
    { q: 'What is the Purpose of an ETag (Entity Tag) HTTP header?', ans: 'A unique fingerprint identifier assigned to a specific version of a resource to enable conditional cache validation (If-None-Match)', d1: 'An electronic price tag for shopping', d2: 'An encryption algorithm name', d3: 'A user session ID' },
  ];
  webData.forEach((w) => {
    addQ(7, 'Web Technologies', 'Medium', w.q, w.ans, w.d1, w.d2, w.d3, (w as any).exp || `Correct resolution: ${w.ans}.`);
  });

  // Level 8: System Design & Distributed Systems (30 distinct questions)
  const sysData = [
    { q: 'Under the CAP Theorem, when a network partition (P) occurs in a distributed system, what fundamental trade-off must be made?', ans: 'Consistency (C) vs Availability (A)', d1: 'Latency vs Throughput', d2: 'Storage vs Memory', d3: 'Security vs Speed' },
    { q: 'What does PACELC Theorem state regarding distributed systems when there is NO partition (Else)?', ans: 'Else: trade-off between Latency (L) and Consistency (C)', d1: 'Else: choose Security over Storage', d2: 'Else: eliminate all caches', d3: 'Else: double server capacity' },
    { q: 'What is Consistent Hashing primarily used for in distributed caching and storage clusters?', ans: 'To minimize key remapping when cache nodes are added or removed dynamically', d1: 'To encrypt user passwords', d2: 'To generate UUIDs', d3: 'To sort arrays in memory' },
    { q: 'What is the function of Virtual Nodes (Vnodes) in Consistent Hashing rings?', ans: 'To distribute keys more uniformly across physical servers and prevent hotspot imbalances', d1: 'To create virtual machines in the cloud', d2: 'To simulate network packet drops', d3: 'To compress cached objects' },
    { q: 'What is a Reverse Proxy (such as Nginx or Envoy)?', ans: 'An intermediary server that sits in front of backend web servers, handling load balancing, TLS termination, and request routing', d1: 'A proxy used by employees to browse the web', d2: 'A database query parser', d3: 'A local hard drive cache' },
    { q: 'What is the difference between Horizontal Scaling (Scale-Out) and Vertical Scaling (Scale-Up)?', ans: 'Horizontal adds more machine instances; Vertical adds more CPU/RAM/capacity to a single existing machine', d1: 'Horizontal is for databases only, Vertical is for web apps', d2: 'Vertical is always cheaper than Horizontal', d3: 'Horizontal replaces all servers daily' },
    { q: 'What is the Circuit Breaker pattern in microservices architecture?', ans: 'A resilience pattern that halts requests to a failing downstream service to prevent cascading failures and allow recovery', d1: 'A physical switch in a server rack', d2: 'An electrical power breaker', d3: 'A tool that terminates running containers' },
    { q: 'What is the Write-Through caching strategy?', ans: 'Data is written simultaneously to the cache and the underlying persistent database before confirming success', d1: 'Data is written to cache only and written to DB lazily', d2: 'Cache is updated only on read misses', d3: 'Writes bypass cache completely' },
    { q: 'What is the Write-Back (Write-Behind) caching strategy?', ans: 'Data is written directly to cache and acknowledged immediately; asynchronous background tasks write dirty entries to the database later', d1: 'Data is written to DB first, cache never', d2: 'Data is read from backup tape', d3: 'Cache is wiped after every write' },
    { q: 'What is the Cache-Aside (Lazy Loading) pattern?', ans: 'The application queries the cache first; on a cache miss, it reads from the database and populates the cache for future requests', d1: 'Database updates the cache automatically', d2: 'All data is cached in advance on startup', d3: 'Cache is never used for reads' },
    { q: 'What is a Bloom Filter in distributed databases (e.g. Cassandra, Bigtable)?', ans: 'A space-efficient probabilistic data structure used to test whether an element is definitely not in a set or might be in a set', d1: 'A filter for water cooling systems', d2: 'A sorting algorithm for strings', d3: 'A visual CSS image filter' },
    { q: 'What is the Single Point of Failure (SPOF) in system design?', ans: 'Any individual component whose failure will cause the entire system or service to cease functioning', d1: 'A software bug in a CSS file', d2: 'A slow internet connection on one client', d3: 'An expired user password' },
    { q: 'What is an Idempotent API endpoint?', ans: 'An endpoint where making multiple identical requests has the exact same side-effect and resulting server state as making a single request', d1: 'An endpoint that requires no authentication', d2: 'An endpoint that returns data in under 1ms', d3: 'An endpoint that accepts only XML' },
    { q: 'What is Eventual Consistency in distributed databases (e.g. DynamoDB, Cassandra)?', ans: 'A consistency model where if no new updates are made, all replicas will eventually converge and return the same data', d1: 'Data is guaranteed consistent instantly across all nodes', d2: 'Data is never updated', d3: 'Transactions are executed sequentially on a single node' },
    { q: 'What is the Split-Brain scenario in a distributed cluster with consensus algorithms?', ans: 'A network partition divides a cluster into two sub-clusters, each believing it is the sole active master, risking data divergence', d1: 'A multicore CPU running out of cache', d2: 'Two developers editing the same file', d3: 'A database query returning conflicting schemas' },
    { q: 'How does the Raft or Paxos consensus algorithm prevent Split-Brain during leader elections?', ans: 'By requiring an absolute majority quorum (more than N/2 nodes) to elect a leader or commit log entries', d1: 'By picking the server with the highest IP address', d2: 'By restarting all nodes every hour', d3: 'By using an external hardware clock' },
    { q: 'What is CQRS (Command Query Responsibility Segregation)?', ans: 'An architectural pattern that separates read operations (queries) from write operations (commands) into distinct models', d1: 'A method to compress database tables', d2: 'A protocol for sending emails', d3: 'A CSS framework for responsive UI' },
    { q: 'What is Event Sourcing pattern?', ans: 'Storing the state of a business entity as an append-only sequence of immutable state-changing domain events', d1: 'Writing source code during meetings', d2: 'Tracking user mouse clicks for analytics', d3: 'Sourcing components from open-source libraries' },
    { q: 'What is Rate Limiting using the Token Bucket algorithm?', ans: 'Tokens are added to a bucket at a fixed rate; requests consume tokens and are rejected or delayed when the bucket is empty, allowing bursts up to capacity', d1: 'Limiting internet bandwidth to 1MB/s', d2: 'Counting total website visitors per year', d3: 'Limiting database column sizes' },
    { q: 'What is Rate Limiting using the Leaky Bucket algorithm?', ans: 'Requests enter a queue and are processed at a smooth, constant output rate regardless of incoming burst traffic', d1: 'Letting memory leak to free space', d2: 'Dropping all network packets randomly', d3: 'Refreshing browser pages periodically' },
    { q: 'What is Database Read Replication primarily used for?', ans: 'To scale out read query throughput by offloading read traffic from the primary write master to multiple read-only replica instances', d1: 'To make write transactions faster', d2: 'To replace database backups', d3: 'To reduce network bandwidth usage' },
    { q: 'What is Data Replication Lag in asynchronous database clusters?', ans: 'The brief time delay between a write committed on the primary master and its propagation/application on replica nodes', d1: 'The physical network cable latency', d2: 'The time taken to compile SQL queries', d3: 'The delay in typing on a keyboard' },
    { q: 'What is the purpose of Message Queues (e.g. Apache Kafka, RabbitMQ) in distributed systems?', ans: 'To decouple producer and consumer services, buffer traffic spikes, and enable asynchronous message processing', d1: 'To store static website images', d2: 'To render server-side HTML templates', d3: 'To authenticate user passwords' },
    { q: 'What is the difference between At-Least-Once and Exactly-Once message delivery semantics?', ans: 'At-Least-Once guarantees messages are never lost but may cause duplicates; Exactly-Once guarantees each message is processed without loss or duplication', d1: 'At-Least-Once is slower than Exactly-Once', d2: 'Exactly-Once does not require acknowledgments', d3: 'At-Least-Once drops messages during failures' },
    { q: 'What is a Distributed Lock (e.g. using Redis Redlock or ZooKeeper)?', ans: 'A mechanism to ensure mutual exclusion across multiple distinct server processes accessing a shared distributed resource', d1: 'A physical lock on server rack doors', d2: 'Encrypting a database with RSA', d3: 'A local mutex in a single process' },
    { q: 'What is Database Connection Pooling?', ans: 'Maintaining a cache of pre-established database connections that can be reused for incoming queries rather than creating a new connection each time', d1: 'Combining multiple databases into one table', d2: 'Sharing WiFi connections among servers', d3: 'Pooling money to pay for cloud hosting' },
    { q: 'What is a Microservices API Gateway pattern?', ans: 'A single entry-point service that handles routing, authentication, SSL termination, rate limiting, and request aggregation for downstream services', d1: 'A router in a home network', d2: 'A database table storing API keys', d3: 'A firewall blocking port 80' },
    { q: 'What is Service Discovery in microservices architectures (e.g. Consul, Eureka)?', ans: 'A dynamic registry that allows service instances to register their network locations (IP/port) and discover other active service instances', d1: 'Finding open-source libraries on GitHub', d2: 'Scanning for open WiFi networks', d3: 'Discovering hard drives attached to servers' },
    { q: 'What is Distributed Tracing (e.g. Jaeger, OpenTelemetry)?', ans: 'Tracking request lifecycles across multiple distributed service boundaries using a shared correlation/trace ID to monitor latency and pinpoint errors', d1: 'Tracking user mouse movements', d2: 'Tracing physical electrical wires', d3: 'Recording audio calls for training' },
    { q: 'What is Database Shard Key Selection critical for?', ans: 'Ensuring even data distribution across shards to prevent hotspot shards from receiving disproportionate write or read load', d1: 'Choosing the color of the server rack', d2: 'Determining SQL query font size', d3: 'Encrypting table column names' },
  ];
  sysData.forEach((s) => {
    addQ(8, 'System Design', 'Hard', s.q, s.ans, s.d1, s.d2, s.d3, (s as any).exp || `Correct resolution: ${s.ans}.`);
  });

  // Level 9: Cloud Computing & DevOps (30 distinct questions)
  const cloudData = [
    { q: 'In Kubernetes cluster orchestration, what is the smallest deployable execution unit that encapsulates one or more containers?', ans: 'Pod', d1: 'Node', d2: 'Deployment', d3: 'Ingress' },
    { q: 'What is a Kubernetes Deployment controller responsible for?', ans: 'Managing declarative declarative replica sets, automated rolling updates, and rollbacks of application Pods', d1: 'Assigning IP addresses to physical cables', d2: 'Compiling Docker images from source', d3: 'Managing hardware power supplies' },
    { q: 'What is the function of a Kubernetes Service object?', ans: 'To provide a stable network IP and DNS name that load-balances traffic across a dynamic set of Pods', d1: 'To store secrets on disk', d2: 'To schedule cron jobs', d3: 'To format hard drive partitions' },
    { q: 'What is Infrastructure as Code (IaC) (e.g. Terraform, Pulumi, CloudFormation)?', ans: 'Managing and provisioning cloud infrastructure, networks, and resources through declarative configuration files rather than manual UI clicks', d1: 'Writing software code on cloud virtual machines', d2: 'Compiling operating system kernels', d3: 'Creating digital architecture diagrams' },
    { q: 'What is Docker containerization?', ans: 'An OS-level virtualization technology that packages applications and dependencies into isolated user-space containers sharing the host OS kernel', d1: 'Hardware virtualization with dedicated guest OS kernels', d2: 'A cloud hosting subscription model', d3: 'A programming language for servers' },
    { q: 'What is the primary difference between a Virtual Machine (VM) and a Docker Container?', ans: 'VMs run a full guest OS on top of a hypervisor; containers share the host OS kernel and isolate user-space processes', d1: 'Containers require more RAM than VMs', d2: 'VMs cannot run Linux', d3: 'Containers cannot execute networked applications' },
    { q: 'What is Continuous Integration (CI)?', ans: 'The development practice of frequently integrating code into a shared repository where automated builds and tests run on every commit', d1: 'Deploying code once a year', d2: 'Writing manual test scripts on paper', d3: 'Hiring external software auditors' },
    { q: 'What is Continuous Deployment (CD)?', ans: 'Automatically releasing every validated build that passes the automated CI test pipeline directly into production environments', d1: 'Writing code without version control', d2: 'Deploying only after manual committee meetings', d3: 'Rebooting servers every night' },
    { q: 'What is a Blue-Green Deployment strategy?', ans: 'Maintaining two identical production environments (Blue and Green); routing live traffic to the newly deployed environment once verified', d1: 'Deploying on Earth Day only', d2: 'Using two different cloud vendors simultaneously', d3: 'Changing the UI background colors' },
    { q: 'What is a Canary Deployment strategy?', ans: 'Rolling out a new software version to a small subset (e.g. 5%) of users first, monitoring metrics, and gradually expanding rollout if stable', d1: 'Testing code inside bird enclosures', d2: 'Deploying code without running tests', d3: 'Shutting down production for maintenance' },
    { q: 'What is Serverless Computing (FaaS, e.g. AWS Lambda, Cloud Run, Azure Functions)?', ans: 'An execution model where cloud providers dynamically manage server allocation and execute code in response to events, billing purely per execution', d1: 'Running computers without any motherboards', d2: 'Storing data on paper instead of disks', d3: 'Writing software without any APIs' },
    { q: 'What is Object Storage (e.g. AWS S3, Google Cloud Storage, Azure Blob)?', ans: 'A scalable flat storage architecture that manages unstructured data as objects with unique IDs and rich metadata accessed over HTTP APIs', d1: 'A block storage device attached to a VM', d2: 'An in-memory relational database', d3: 'A local CPU register cache' },
    { q: 'What is Block Storage (e.g. AWS EBS, Persistent Disk)?', ans: 'Raw storage volumes that can be attached to virtual machines and formatted with a file system like ext4 or NTFS', d1: 'A key-value store for JSON documents', d2: 'A content delivery network for images', d3: 'An email archive service' },
    { q: 'What is a Content Delivery Network (CDN) (e.g. Cloudflare, CloudFront, Fastly)?', ans: 'A geographically distributed network of proxy edge servers that cache content close to end users to reduce latency and origin server load', d1: 'A television broadcasting satellite', d2: 'A cloud database for storing financial records', d3: 'A fiber optic cable company' },
    { q: 'What is Auto-Scaling in cloud infrastructure?', ans: 'Automatically adjusting the number of active server instances up or down based on real-time metrics like CPU usage or request count', d1: 'Automatically increasing font size on mobile screens', d2: 'Scaling image resolutions in CSS', d3: 'Upgrading internet speed subscriptions' },
    { q: 'What is the role of Kubernetes Ingress controller (e.g. NGINX Ingress, Traefik)?', ans: 'To manage external HTTP/HTTPS routing into cluster Services, providing SSL termination and name-based virtual hosting', d1: 'To schedule cron backup jobs', d2: 'To scan Docker images for malware', d3: 'To allocate RAM to worker nodes' },
    { q: 'What is GitOps in DevOps workflows?', ans: 'An operational framework where Git repositories serve as the single source of truth for declaratively managing infrastructure and application deployments', d1: 'Using Git only for tracking bug tickets', d2: 'A cloud provider competing with AWS', d3: 'Writing Git commands manually on production servers' },
    { q: 'What is Prometheus in cloud-native monitoring?', ans: 'An open-source monitoring and alerting toolkit that scrapes time-series numerical metrics from monitored targets over HTTP', d1: 'A log aggregation database', d2: 'A container orchestrator', d3: 'A continuous deployment pipeline' },
    { q: 'What is Grafana commonly used for in DevOps monitoring stacks?', ans: 'Visualizing time-series metrics, logs, and traces through interactive customizable dashboards', d1: 'Executing unit tests', d2: 'Managing DNS records', d3: 'Creating Docker images' },
    { q: 'What is a Rolling Update in container orchestration?', ans: 'Incrementally replacing instances of the old application version with instances of the new version with zero downtime', d1: 'Restarting all servers at the same instant', d2: 'Deleting all database records before deploying', d3: 'Updating only developer laptops' },
    { q: 'What does Multi-Zone or Multi-Region redundancy achieve in cloud architecture?', ans: 'High availability and disaster recovery by ensuring service continuity even if an entire physical data center or geographic region fails', d1: 'Lowering cloud hosting bills by 90%', d2: 'Eliminating the need for software testing', d3: 'Making all API calls synchronous' },
    { q: 'What is the purpose of a Dockerfile in container engineering?', ans: 'A text script containing sequential commands and instructions to automatically build a standalone container image', d1: 'A file containing user passwords', d2: 'A network routing table for containers', d3: 'A system crash log' },
    { q: 'What is a Helm Chart in Kubernetes ecosystems?', ans: 'A package manager template collection that defines, installs, and manages complex Kubernetes applications', d1: 'A visual architecture drawing', d2: 'A hardware rack blueprint', d3: 'A time tracking chart for developers' },
    { q: 'What is a Service Mesh (e.g. Istio, Linkerd)?', ans: 'A dedicated infrastructure layer of sidecar proxies managing service-to-service communication, mTLS encryption, traffic routing, and observability', d1: 'A physical mesh of network cables', d2: 'A UI wireframe component grid', d3: 'A database clustering tool' },
    { q: 'What is Configuration Drift in cloud infrastructure management?', ans: 'The divergence between the actual live state of cloud resources and the declarative state defined in source code (IaC)', d1: 'A computer mouse drifting across the screen', d2: 'Network packets arriving out of order', d3: 'Developers forgetting their passwords' },
    { q: 'What is the purpose of Kubernetes ConfigMaps and Secrets?', ans: 'To decouple configuration parameters and sensitive credentials from container image code for flexible environment-specific injection', d1: 'To compile Go source code', d2: 'To generate SSL certificates automatically', d3: 'To format SSD block storage' },
    { q: 'What is Chaos Engineering (e.g. Chaos Monkey)?', ans: 'The discipline of intentionally injecting failures (e.g. killing instances, dropping network packets) into production systems to test resilience', d1: 'Writing unformatted spaghetti code', d2: 'Deleting customer accounts randomly', d3: 'Deploying software without testing' },
    { q: 'What is a Reverse DNS lookup in networking?', ans: 'Querying the DNS system to determine the domain hostname associated with a given IP address (using PTR records)', d1: 'Translating hostnames to IP addresses', d2: 'Deleting domain registrations', d3: 'Blocking IP addresses in firewalls' },
    { q: 'What is an Edge Computing architecture?', ans: 'Processing computational workloads and data analysis near the physical source of data (edge nodes/devices) rather than in centralized cloud datacenters', d1: 'Building servers at the edge of a desk', d2: 'Running algorithms on the perimeter of an image', d3: 'Using Microsoft Edge browser exclusively' },
    { q: 'What is a Cloud VPC (Virtual Private Cloud)?', ans: 'An isolated, logically separated private virtual network within a public cloud provider where users provision their compute and database resources', d1: 'A physical server dedicated to one user', d2: 'A VPN client installed on mobile phones', d3: 'A cloud billing invoice' },
  ];
  cloudData.forEach((c) => {
    addQ(9, 'Cloud & DevOps', 'Medium', c.q, c.ans, c.d1, c.d2, c.d3, (c as any).exp || `Correct resolution: ${c.ans}.`);
  });

  // Level 10: Cybersecurity & Cryptography (30 distinct questions)
  const secData = [
    { q: 'Which cryptographic construct provides deterministic, fixed-length digests and one-way irreversible computation?', ans: 'Cryptographic Hash Function (e.g. SHA-256, BLAKE3)', d1: 'Symmetric Block Cipher (e.g. AES-256)', d2: 'Asymmetric Key Pair (e.g. RSA-4096)', d3: 'Diffie-Hellman Key Exchange' },
    { q: 'What is the primary difference between Symmetric and Asymmetric encryption?', ans: 'Symmetric uses the same shared secret key for encryption and decryption; Asymmetric uses a mathematically paired public and private key', d1: 'Symmetric is always unencrypted', d2: 'Asymmetric cannot encrypt data', d3: 'Symmetric only runs on hardware' },
    { q: 'Which industry-standard symmetric block cipher uses 128, 192, or 256-bit keys and operates on 128-bit blocks?', ans: 'AES (Advanced Encryption Standard)', d1: 'RSA', d2: 'Diffie-Hellman', d3: 'MD5' },
    { q: 'What is SQL Injection (SQLi) and how is it primarily prevented?', ans: 'An attack injecting malicious SQL fragments into input fields; prevented by using Parameterized Queries / Prepared Statements', d1: 'An attack that deletes CSS files; prevented by using dark mode', d2: 'An attack that shuts down servers; prevented by using batteries', d3: 'An attack on network routers; prevented by buying firewalls' },
    { q: 'What is Cross-Site Scripting (XSS)?', ans: 'A vulnerability where an attacker injects malicious client-side script code into a web application viewed by other users', d1: 'An attack that crashes the web server CPU', d2: 'An attack that guesses passwords', d3: 'A database table deletion technique' },
    { q: 'What is Cross-Site Request Forgery (CSRF)?', ans: 'An attack that tricks an authenticated user\'s browser into executing unwanted actions on a trusted web application where they are currently authenticated', d1: 'Stealing physical computer hardware', d2: 'Injecting malicious SQL statements', d3: 'Cracking Wi-Fi passwords' },
    { q: 'What is the purpose of Salting passwords before hashing?', ans: 'Appending a unique random string to each password before hashing to defend against Rainbow Table attacks and duplicate hash lookups', d1: 'Encrypting passwords with salt minerals', d2: 'Making passwords shorter and easier to type', d3: 'Sending passwords over plain HTTP' },
    { q: 'Why is bcrypt or Argon2 preferred over MD5 or SHA-256 for password hashing?', ans: 'They incorporate configurable computational work factors (key stretching) to make brute-force and GPU hardware attacks prohibitively slow', d1: 'They produce shorter hash strings', d2: 'They allow passwords to be decrypted easily by admins', d3: 'They require no CPU memory' },
    { q: 'What is a Man-in-the-Middle (MITM) attack?', ans: 'An attack where an adversary secretly intercepts and potentially alters communication between two parties who believe they are communicating directly', d1: 'An employee sitting between two desks', d2: 'A physical firewall in an office', d3: 'A server rebooting during peak hours' },
    { q: 'What is the primary role of a Certificate Authority (CA) in Public Key Infrastructure (PKI)?', ans: 'To digitally sign and validate X.509 SSL/TLS certificates, binding a public key to an authenticated organization domain', d1: 'To store all user passwords in the cloud', d2: 'To route internet traffic across continents', d3: 'To manufacture computer microchips' },
    { q: 'What is Diffie-Hellman Key Exchange used for?', ans: 'A method allowing two parties to securely establish a shared secret key over an insecure, public communication channel', d1: 'Encrypting files on a local USB drive', d2: 'Signing PDF documents legally', d3: 'Compressing video files' },
    { q: 'What is Multi-Factor Authentication (MFA)?', ans: 'A security mechanism requiring users to present two or more independent authentication factors (knowledge, possession, inherence)', d1: 'Using two different passwords for the same account', d2: 'Logging in from two computers simultaneously', d3: 'Typing a password twice' },
    { q: 'What is a Zero-Day Vulnerability?', ans: 'A software security flaw that is known to attackers or researchers but has no official security patch released by the vendor', d1: 'A bug discovered within 0 days of hiring a developer', d2: 'A software release with zero errors', d3: 'A computer virus that operates for zero seconds' },
    { q: 'What is a Distributed Denial of Service (DDoS) attack?', ans: 'An attempt to overwhelm a target server, service, or network with a flood of traffic from multiple compromised distributed botnet systems', d1: 'A physical server cable being cut', d2: 'A single developer making a typo in code', d3: 'A database query timing out' },
    { q: 'What is the Principle of Least Privilege (PoLP)?', ans: 'A security design rule that every user, process, and program should be granted only the minimum permissions necessary to perform its legitimate function', d1: 'Giving all users full administrator root access', d2: 'Denying all employees access to computers', d3: 'Deleting user accounts daily' },
    { q: 'What is a Replay Attack and how is it mitigated in cryptographic network protocols?', ans: 'An attacker captures valid authentication traffic and transmits it again later; mitigated using timestamps, session nonces, and unique message IDs', d1: 'Playing an audio recording in an office', d2: 'Rewatching a video on YouTube', d3: 'Re-running a compiler build' },
    { q: 'What is a Buffer Overflow attack?', ans: 'Writing more data to a fixed-size memory buffer than it can hold, overwriting adjacent memory (such as return addresses) to execute arbitrary code', d1: 'A network queue filling up', d2: 'A hard disk running out of storage space', d3: 'A monitor displaying too many colors' },
    { q: 'What is Address Space Layout Randomization (ASLR)?', ans: 'An operating system defense that randomizes the memory addresses of key program areas (stack, heap, libraries) to thwart buffer overflow exploits', d1: 'Assigning random IP addresses to network routers', d2: 'Randomizing file names on disk', d3: 'Shuffling array elements in memory' },
    { q: 'What is a Digital Signature and what security guarantees does it provide?', ans: 'A cryptographic hash of data encrypted with the sender\'s private key, providing authenticity, integrity, and non-repudiation', d1: 'A scanned image of a handwritten signature', d2: 'A user login password', d3: 'A company logo on a website' },
    { q: 'What is Non-Repudiation in information security?', ans: 'The assurance that a party to a communication or transaction cannot deny the authenticity of their signature or action', d1: 'Refusing to refund customer purchases', d2: 'Preventing password changes', d3: 'Deleting transaction history' },
    { q: 'What is Penetration Testing (Ethical Hacking)?', ans: 'An authorized simulated cyberattack on a computer system performed to evaluate its security posture and identify vulnerabilities', d1: 'Testing hardware durability with a hammer', d2: 'Writing unverified code in production', d3: 'Installing pirated software' },
    { q: 'What is a Honeypot in network security?', ans: 'A decoy computer system intended to mimic likely targets of cyberattacks to detect, deflect, or study attacker methods', d1: 'A jar of honey stored in a server room', d2: 'A high-speed database cache', d3: 'A tool for cleaning computer screens' },
    { q: 'What is Phishing?', ans: 'A social engineering attack where adversaries impersonate legitimate institutions via email or messaging to trick individuals into disclosing sensitive credentials', d1: 'Catching fish with a fishing rod', d2: 'Scanning for open ports with Nmap', d3: 'Writing code without documentation' },
    { q: 'What is Ransomware?', ans: 'Malicious software that encrypts a victim\'s files and demands payment in exchange for the decryption key', d1: 'Software purchased with a company credit card', d2: 'An open-source software license', d3: 'A database backup utility' },
    { q: 'What is the role of Perfect Forward Secrecy (PFS) in TLS handshakes?', ans: 'Ensuring that compromise of a long-term private server key does not compromise past session keys or decrypt past recorded traffic', d1: 'Preventing servers from crashing', d2: 'Encrypting data with symmetric keys only', d3: 'Speeding up internet downloads' },
    { q: 'What is a Rootkit in operating systems security?', ans: 'Stealthy malicious software designed to hide its presence and grant administrative privileged access to a computer system below OS detection', d1: 'The root user password in Linux', d2: 'A utility for partitioning hard drives', d3: 'A motherboard chip manufacturing kit' },
    { q: 'What does the OWASP Top 10 represent in cybersecurity?', ans: 'A regularly updated consensus document outlining the ten most critical web application security risks and vulnerabilities', d1: 'A list of top ten computer manufacturers', d2: 'A ranking of fastest supercomputers', d3: 'A top 10 list of software programming languages' },
    { q: 'What is a Side-Channel Attack (e.g. Spectre, Meltdown, timing attacks)?', ans: 'An attack based on information gained from the physical implementation of a computer system (timing, power consumption, acoustic emissions, cache behavior) rather than flaws in the algorithm', d1: 'Attacking a server from the side of the room', d2: 'Injecting SQL into side tables', d3: 'Hacking through a second monitor' },
    { q: 'What is Port Scanning used for in network reconnaissance?', ans: 'Probing a server or host to discover open network ports and identifying active network services and potential vulnerabilities', d1: 'Plugging USB cables into laptop ports', d2: 'Measuring electrical voltage on network ports', d3: 'Cleaning physical Ethernet ports' },
    { q: 'What is a Web Application Firewall (WAF)?', ans: 'A specialized security appliance or reverse proxy that inspects and filters incoming HTTP/HTTPS traffic to block common web attacks like SQLi, XSS, and CSRF', d1: 'A firewall built into home WiFi routers', d2: 'A physical brick wall separating server rooms', d3: 'An antivirus program installed on smartphones' },
  ];
  secData.forEach((s) => {
    addQ(10, 'Cybersecurity', 'Hard', s.q, s.ans, s.d1, s.d2, s.d3, (s as any).exp || `Correct resolution: ${s.ans}.`);
  });

  return list;
}
